services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: user_monev
      POSTGRES_PASSWORD: password_monev
      POSTGRES_DB: monev_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
