SET FOREIGN_KEY_CHECKS = 0;

-- Full MySQL Dump

-- CreateTable
CREATE TABLE `Account` (
    `id` VARCHAR(191) NOT NULL,
    `userId` VARCHAR(191) NOT NULL,
    `type` VARCHAR(191) NOT NULL,
    `provider` VARCHAR(191) NOT NULL,
    `providerAccountId` VARCHAR(191) NOT NULL,
    `refresh_token` TEXT NULL,
    `access_token` TEXT NULL,
    `expires_at` INTEGER NULL,
    `token_type` VARCHAR(191) NULL,
    `scope` VARCHAR(191) NULL,
    `id_token` TEXT NULL,
    `session_state` VARCHAR(191) NULL,

    UNIQUE INDEX `Account_provider_providerAccountId_key`(`provider`, `providerAccountId`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Session` (
    `id` VARCHAR(191) NOT NULL,
    `sessionToken` VARCHAR(191) NOT NULL,
    `userId` VARCHAR(191) NOT NULL,
    `expires` DATETIME(3) NOT NULL,

    UNIQUE INDEX `Session_sessionToken_key`(`sessionToken`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `User` (
    `id` VARCHAR(191) NOT NULL,
    `name` VARCHAR(191) NULL,
    `username` VARCHAR(191) NULL,
    `password` VARCHAR(191) NULL,
    `email` VARCHAR(191) NULL,
    `emailVerified` DATETIME(3) NULL,
    `image` VARCHAR(191) NULL,
    `role` VARCHAR(191) NULL DEFAULT 'GKM',
    `facultyId` VARCHAR(191) NULL,
    `prodiId` VARCHAR(191) NULL,

    UNIQUE INDEX `User_username_key`(`username`),
    UNIQUE INDEX `User_email_key`(`email`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `VerificationToken` (
    `identifier` VARCHAR(191) NOT NULL,
    `token` VARCHAR(191) NOT NULL,
    `expires` DATETIME(3) NOT NULL,

    UNIQUE INDEX `VerificationToken_token_key`(`token`),
    UNIQUE INDEX `VerificationToken_identifier_token_key`(`identifier`, `token`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Level` (
    `id` VARCHAR(191) NOT NULL,
    `name` VARCHAR(191) NOT NULL,

    UNIQUE INDEX `Level_name_key`(`name`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Setting` (
    `id` VARCHAR(191) NOT NULL,
    `appscript_url` VARCHAR(191) NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Cycle` (
    `id` VARCHAR(191) NOT NULL,
    `tahun_akademik` VARCHAR(191) NOT NULL,
    `semester` VARCHAR(191) NOT NULL,
    `isActive` BOOLEAN NOT NULL DEFAULT false,

    UNIQUE INDEX `Cycle_tahun_akademik_semester_key`(`tahun_akademik`, `semester`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Document` (
    `id` VARCHAR(191) NOT NULL,
    `type` VARCHAR(191) NOT NULL,
    `title` VARCHAR(191) NOT NULL,
    `description` TEXT NULL,
    `fileUrl` TEXT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Faculty` (
    `id` VARCHAR(191) NOT NULL,
    `name` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Prodi` (
    `id` VARCHAR(191) NOT NULL,
    `facultyId` VARCHAR(191) NOT NULL,
    `name` VARCHAR(191) NOT NULL,
    `jenjang` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Instrument` (
    `id` VARCHAR(191) NOT NULL,
    `category` VARCHAR(191) NOT NULL,
    `name` VARCHAR(191) NOT NULL,
    `kriteria` VARCHAR(191) NOT NULL,
    `indikator` VARCHAR(191) NOT NULL,
    `jenjang_peruntukan` VARCHAR(191) NOT NULL,
    `questions` TEXT NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `MonevRecord` (
    `id` VARCHAR(191) NOT NULL,
    `prodiId` VARCHAR(191) NOT NULL,
    `instrumentId` VARCHAR(191) NOT NULL,
    `tahun_akademik` VARCHAR(191) NOT NULL,
    `semester` VARCHAR(191) NOT NULL,
    `analisa_kpma` TEXT NULL,
    `tindak_lanjut_kpma` TEXT NULL,
    `answers` TEXT NOT NULL,
    `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    UNIQUE INDEX `MonevRecord_prodiId_instrumentId_tahun_akademik_semester_key`(`prodiId`, `instrumentId`, `tahun_akademik`, `semester`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `Account` ADD CONSTRAINT `Account_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `User`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Session` ADD CONSTRAINT `Session_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `User`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `User` ADD CONSTRAINT `User_facultyId_fkey` FOREIGN KEY (`facultyId`) REFERENCES `Faculty`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `User` ADD CONSTRAINT `User_prodiId_fkey` FOREIGN KEY (`prodiId`) REFERENCES `Prodi`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Prodi` ADD CONSTRAINT `Prodi_facultyId_fkey` FOREIGN KEY (`facultyId`) REFERENCES `Faculty`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `MonevRecord` ADD CONSTRAINT `MonevRecord_prodiId_fkey` FOREIGN KEY (`prodiId`) REFERENCES `Prodi`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `MonevRecord` ADD CONSTRAINT `MonevRecord_instrumentId_fkey` FOREIGN KEY (`instrumentId`) REFERENCES `Instrument`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;



-- Data for table `User`
INSERT INTO `User` (`id`, `name`, `username`, `password`, `email`, `emailVerified`, `image`, `role`, `facultyId`, `prodiId`) VALUES ('cmojchv750001ot94ix779pz7', 'Prodi BKPI', 'bkpi_fai', '$2b$10$2mHf7sRZxCZTMP9qI8pQzejww2Bzq9KBEAhLyfLrqRZmJpHoS8cjq', NULL, NULL, NULL, 'GKM', 'cmoj7qv5y0000ot5occuyj350', 'cmoj7qv6j000eot5o8oiezdnp');
INSERT INTO `User` (`id`, `name`, `username`, `password`, `email`, `emailVerified`, `image`, `role`, `facultyId`, `prodiId`) VALUES ('cmojchv7e0003ot94lb7cygm6', 'Prodi ESY', 'esy_fai', '$2b$10$2mHf7sRZxCZTMP9qI8pQzejww2Bzq9KBEAhLyfLrqRZmJpHoS8cjq', NULL, NULL, NULL, 'GKM', 'cmoj7qv5y0000ot5occuyj350', 'cmoj7qv680006ot5ool6isbco');
INSERT INTO `User` (`id`, `name`, `username`, `password`, `email`, `emailVerified`, `image`, `role`, `facultyId`, `prodiId`) VALUES ('cmojchv7l0005ot94ilbquv80', 'Prodi HKI', 'hki_fai', '$2b$10$2mHf7sRZxCZTMP9qI8pQzejww2Bzq9KBEAhLyfLrqRZmJpHoS8cjq', NULL, NULL, NULL, 'GKM', 'cmoj7qv5y0000ot5occuyj350', 'cmoj7qv6b0008ot5ob31efhe0');
INSERT INTO `User` (`id`, `name`, `username`, `password`, `email`, `emailVerified`, `image`, `role`, `facultyId`, `prodiId`) VALUES ('cmojchv7y0007ot94fke0c4tq', 'Prodi IAT', 'iat_fai', '$2b$10$2mHf7sRZxCZTMP9qI8pQzejww2Bzq9KBEAhLyfLrqRZmJpHoS8cjq', NULL, NULL, NULL, 'GKM', 'cmoj7qv5y0000ot5occuyj350', 'cmoj7qv6e000aot5obu0a6otd');
INSERT INTO `User` (`id`, `name`, `username`, `password`, `email`, `emailVerified`, `image`, `role`, `facultyId`, `prodiId`) VALUES ('cmojchv8c0009ot94bthwokd3', 'Prodi KPI', 'kpi_fai', '$2b$10$2mHf7sRZxCZTMP9qI8pQzejww2Bzq9KBEAhLyfLrqRZmJpHoS8cjq', NULL, NULL, NULL, 'GKM', 'cmoj7qv5y0000ot5occuyj350', 'cmoj7qv6m000got5olmqf5wpx');
INSERT INTO `User` (`id`, `name`, `username`, `password`, `email`, `emailVerified`, `image`, `role`, `facultyId`, `prodiId`) VALUES ('cmojchv8s000bot948b7gq81u', 'Prodi MHU', 'mhu_fai', '$2b$10$2mHf7sRZxCZTMP9qI8pQzejww2Bzq9KBEAhLyfLrqRZmJpHoS8cjq', NULL, NULL, NULL, 'GKM', 'cmoj7qv5y0000ot5occuyj350', 'cmoj7qv6h000cot5o9vzhbsuq');
INSERT INTO `User` (`id`, `name`, `username`, `password`, `email`, `emailVerified`, `image`, `role`, `facultyId`, `prodiId`) VALUES ('cmojchv9a000dot94bn6ukh0j', 'Prodi PAI', 'pai_fai', '$2b$10$2mHf7sRZxCZTMP9qI8pQzejww2Bzq9KBEAhLyfLrqRZmJpHoS8cjq', NULL, NULL, NULL, 'GKM', 'cmoj7qv5y0000ot5occuyj350', 'cmoj7qv620002ot5oxtfoxsxd');
INSERT INTO `User` (`id`, `name`, `username`, `password`, `email`, `emailVerified`, `image`, `role`, `facultyId`, `prodiId`) VALUES ('cmojchv9t000fot9481ampjps', 'Prodi PGMI', 'pgmi_fai', '$2b$10$2mHf7sRZxCZTMP9qI8pQzejww2Bzq9KBEAhLyfLrqRZmJpHoS8cjq', NULL, NULL, NULL, 'GKM', 'cmoj7qv5y0000ot5occuyj350', 'cmoj7qv650004ot5oi5fjswyx');
INSERT INTO `User` (`id`, `name`, `username`, `password`, `email`, `emailVerified`, `image`, `role`, `facultyId`, `prodiId`) VALUES ('cmojchva6000hot94zt6rd3gi', 'Dekanat', 'dekanat', '$2b$10$2mHf7sRZxCZTMP9qI8pQzejww2Bzq9KBEAhLyfLrqRZmJpHoS8cjq', NULL, NULL, NULL, 'PIMPINAN_FAKULTAS', 'cmoj7qv5y0000ot5occuyj350', NULL);
INSERT INTO `User` (`id`, `name`, `username`, `password`, `email`, `emailVerified`, `image`, `role`, `facultyId`, `prodiId`) VALUES ('cmojchvah000jot94o3jopqkq', 'M Faishal Hidayat', 'gpm_fai', '$2b$10$2mHf7sRZxCZTMP9qI8pQzejww2Bzq9KBEAhLyfLrqRZmJpHoS8cjq', NULL, NULL, NULL, 'GPM', 'cmoj7qv5y0000ot5occuyj350', NULL);
INSERT INTO `User` (`id`, `name`, `username`, `password`, `email`, `emailVerified`, `image`, `role`, `facultyId`, `prodiId`) VALUES ('cmojchvau000lot946fl0ru27', 'Perbankan dan Keuangan Digital', 'pkdfeb', '$2b$10$2mHf7sRZxCZTMP9qI8pQzejww2Bzq9KBEAhLyfLrqRZmJpHoS8cjq', NULL, NULL, NULL, 'GKM', 'cmoj7qv77000sot5oor0zjdjz', 'cmoj7qv7l0012ot5o02rbjsr9');
INSERT INTO `User` (`id`, `name`, `username`, `password`, `email`, `emailVerified`, `image`, `role`, `facultyId`, `prodiId`) VALUES ('cmojchvb5000not941exvt8a3', 'Akuntansi', 'akuntansi', '$2b$10$2mHf7sRZxCZTMP9qI8pQzejww2Bzq9KBEAhLyfLrqRZmJpHoS8cjq', NULL, NULL, NULL, 'GKM', 'cmoj7qv77000sot5oor0zjdjz', 'cmoj7qv7a000uot5ormt5ecrc');
INSERT INTO `User` (`id`, `name`, `username`, `password`, `email`, `emailVerified`, `image`, `role`, `facultyId`, `prodiId`) VALUES ('cmojchvbi000pot945kexkrce', 'Bisnis Digital', 'bdfeb', '$2b$10$2mHf7sRZxCZTMP9qI8pQzejww2Bzq9KBEAhLyfLrqRZmJpHoS8cjq', NULL, NULL, NULL, 'GKM', 'cmoj7qv77000sot5oor0zjdjz', 'cmoj7qv7i0010ot5oe18c2p65');
INSERT INTO `User` (`id`, `name`, `username`, `password`, `email`, `emailVerified`, `image`, `role`, `facultyId`, `prodiId`) VALUES ('cmojchvbu000rot94r8wmka23', 'Manajemen', 'manajemen', '$2b$10$2mHf7sRZxCZTMP9qI8pQzejww2Bzq9KBEAhLyfLrqRZmJpHoS8cjq', NULL, NULL, NULL, 'GKM', 'cmoj7qv77000sot5oor0zjdjz', 'cmoj7qv6h000cot5o9vzhbsuq');
INSERT INTO `User` (`id`, `name`, `username`, `password`, `email`, `emailVerified`, `image`, `role`, `facultyId`, `prodiId`) VALUES ('cmojchvc5000tot944wylsoq9', 'Perdagangan Internasional', 'pifeb', '$2b$10$2mHf7sRZxCZTMP9qI8pQzejww2Bzq9KBEAhLyfLrqRZmJpHoS8cjq', NULL, NULL, NULL, 'GKM', 'cmoj7qv77000sot5oor0zjdjz', 'cmoj7qv7f000yot5ot7aa4g10');
INSERT INTO `User` (`id`, `name`, `username`, `password`, `email`, `emailVerified`, `image`, `role`, `facultyId`, `prodiId`) VALUES ('cmojchvch000vot94b45plw4t', 'Dekanat FEB', 'dekanat_feb', '$2b$10$2mHf7sRZxCZTMP9qI8pQzejww2Bzq9KBEAhLyfLrqRZmJpHoS8cjq', NULL, NULL, NULL, 'PIMPINAN_FAKULTAS', 'cmoj7qv77000sot5oor0zjdjz', NULL);
INSERT INTO `User` (`id`, `name`, `username`, `password`, `email`, `emailVerified`, `image`, `role`, `facultyId`, `prodiId`) VALUES ('cmojchvct000xot940ui9u9wi', 'GPM', 'gpm_feb', '$2b$10$2mHf7sRZxCZTMP9qI8pQzejww2Bzq9KBEAhLyfLrqRZmJpHoS8cjq', NULL, NULL, NULL, 'GPM', 'cmoj7qv77000sot5oor0zjdjz', NULL);
INSERT INTO `User` (`id`, `name`, `username`, `password`, `email`, `emailVerified`, `image`, `role`, `facultyId`, `prodiId`) VALUES ('cmojchvd5000zot94hd2ydln6', 'Dr. Desti Anggi Mustika, S.H., M.H. (S1)', 'ilmuhukum', '$2b$10$2mHf7sRZxCZTMP9qI8pQzejww2Bzq9KBEAhLyfLrqRZmJpHoS8cjq', NULL, NULL, NULL, 'GKM', 'cmoj7qv7o0013ot5ocepb6wzd', 'cmoj7qv7r0015ot5oo685f5us');
INSERT INTO `User` (`id`, `name`, `username`, `password`, `email`, `emailVerified`, `image`, `role`, `facultyId`, `prodiId`) VALUES ('cmojchvdh0011ot94uh4dxppr', 'Dr. Desti Anggi Mustika, S.H., M.H. (S2)', 'ilmuhukum_s2', '$2b$10$2mHf7sRZxCZTMP9qI8pQzejww2Bzq9KBEAhLyfLrqRZmJpHoS8cjq', NULL, NULL, NULL, 'GKM', 'cmoj7qv7o0013ot5ocepb6wzd', 'cmoj7qv7u0017ot5o0r0ysdau');
INSERT INTO `User` (`id`, `name`, `username`, `password`, `email`, `emailVerified`, `image`, `role`, `facultyId`, `prodiId`) VALUES ('cmojchvdt0013ot94w8ypcv0v', 'Dekanat FH', 'dekanat_fh', '$2b$10$2mHf7sRZxCZTMP9qI8pQzejww2Bzq9KBEAhLyfLrqRZmJpHoS8cjq', NULL, NULL, NULL, 'PIMPINAN_FAKULTAS', 'cmoj7qv7o0013ot5ocepb6wzd', NULL);
INSERT INTO `User` (`id`, `name`, `username`, `password`, `email`, `emailVerified`, `image`, `role`, `facultyId`, `prodiId`) VALUES ('cmojchve40015ot94qjz5s3fg', 'Latifah Ratnawaty, S.H., M.H.', 'gpm_fh', '$2b$10$2mHf7sRZxCZTMP9qI8pQzejww2Bzq9KBEAhLyfLrqRZmJpHoS8cjq', NULL, NULL, NULL, 'GPM', 'cmoj7qv7o0013ot5ocepb6wzd', NULL);
INSERT INTO `User` (`id`, `name`, `username`, `password`, `email`, `emailVerified`, `image`, `role`, `facultyId`, `prodiId`) VALUES ('cmojchvef0017ot94yxqpdvot', 'Gizi', 'gizi_fikes', '$2b$10$2mHf7sRZxCZTMP9qI8pQzejww2Bzq9KBEAhLyfLrqRZmJpHoS8cjq', NULL, NULL, NULL, 'GKM', 'cmoj7qv8k001not5on41vuh1a', 'cmoj7qv8q001rot5o633hdgl4');
INSERT INTO `User` (`id`, `name`, `username`, `password`, `email`, `emailVerified`, `image`, `role`, `facultyId`, `prodiId`) VALUES ('cmojchver0019ot94my6mfv47', 'Kesehatan Masyarakat', 'kesmas_fikes', '$2b$10$2mHf7sRZxCZTMP9qI8pQzejww2Bzq9KBEAhLyfLrqRZmJpHoS8cjq', NULL, NULL, NULL, 'GKM', 'cmoj7qv8k001not5on41vuh1a', 'cmoj7qv8n001pot5onhv18sh6');
INSERT INTO `User` (`id`, `name`, `username`, `password`, `email`, `emailVerified`, `image`, `role`, `facultyId`, `prodiId`) VALUES ('cmojchvf0001bot94h88fadlf', 'Dekanat Fikes', 'dekanat_fikes', '$2b$10$2mHf7sRZxCZTMP9qI8pQzejww2Bzq9KBEAhLyfLrqRZmJpHoS8cjq', NULL, NULL, NULL, 'PIMPINAN_FAKULTAS', 'cmoj7qv8k001not5on41vuh1a', NULL);
INSERT INTO `User` (`id`, `name`, `username`, `password`, `email`, `emailVerified`, `image`, `role`, `facultyId`, `prodiId`) VALUES ('cmojchvfc001dot94n0ej41hi', 'GPM FIKES', 'gpm_fikes', '$2b$10$2mHf7sRZxCZTMP9qI8pQzejww2Bzq9KBEAhLyfLrqRZmJpHoS8cjq', NULL, NULL, NULL, 'GPM', 'cmoj7qv8k001not5on41vuh1a', NULL);
INSERT INTO `User` (`id`, `name`, `username`, `password`, `email`, `emailVerified`, `image`, `role`, `facultyId`, `prodiId`) VALUES ('cmojchvfo001fot94y6i0dwr2', 'Pendidikan Bahasa Inggris', 'pbi_fkip', '$2b$10$2mHf7sRZxCZTMP9qI8pQzejww2Bzq9KBEAhLyfLrqRZmJpHoS8cjq', NULL, NULL, NULL, 'GKM', 'cmoj7qv6p000hot5o7xgokreq', 'cmoj7qv6t000jot5o0xxsc6vx');
INSERT INTO `User` (`id`, `name`, `username`, `password`, `email`, `emailVerified`, `image`, `role`, `facultyId`, `prodiId`) VALUES ('cmojchvg0001hot94u5atueyi', 'Kartika Ayu Ningsih, M.Pd.', 'penmas', '$2b$10$2mHf7sRZxCZTMP9qI8pQzejww2Bzq9KBEAhLyfLrqRZmJpHoS8cjq', NULL, NULL, NULL, 'GKM', 'cmoj7qv6p000hot5o7xgokreq', 'cmoj7qv6w000lot5o1tywnh6y');
INSERT INTO `User` (`id`, `name`, `username`, `password`, `email`, `emailVerified`, `image`, `role`, `facultyId`, `prodiId`) VALUES ('cmojchvgc001jot94lfpaddxa', 'pulan', 'penmat', '$2b$10$2mHf7sRZxCZTMP9qI8pQzejww2Bzq9KBEAhLyfLrqRZmJpHoS8cjq', NULL, NULL, NULL, 'GKM', 'cmoj7qv6p000hot5o7xgokreq', 'cmoj7qv6z000not5oqpc6c218');
INSERT INTO `User` (`id`, `name`, `username`, `password`, `email`, `emailVerified`, `image`, `role`, `facultyId`, `prodiId`) VALUES ('cmojchvgn001lot947cjl75jf', 'Pendidikan Vokasional Desain Fashion', 'pvdf_fkip', '$2b$10$2mHf7sRZxCZTMP9qI8pQzejww2Bzq9KBEAhLyfLrqRZmJpHoS8cjq', NULL, NULL, NULL, 'GKM', 'cmoj7qv6p000hot5o7xgokreq', 'cmoj7qv72000pot5ou2eqq7uo');
INSERT INTO `User` (`id`, `name`, `username`, `password`, `email`, `emailVerified`, `image`, `role`, `facultyId`, `prodiId`) VALUES ('cmojchvgz001not94fwxi2jqx', 'Teknologi Pendidikan', 'tp_fkip', '$2b$10$2mHf7sRZxCZTMP9qI8pQzejww2Bzq9KBEAhLyfLrqRZmJpHoS8cjq', NULL, NULL, NULL, 'GKM', 'cmoj7qv6p000hot5o7xgokreq', 'cmoj7qv74000rot5oa1ml9jfr');
INSERT INTO `User` (`id`, `name`, `username`, `password`, `email`, `emailVerified`, `image`, `role`, `facultyId`, `prodiId`) VALUES ('cmojchvie001pot9469ts27na', 'Dekanat FKIP', 'dekanat_fkip', '$2b$10$2mHf7sRZxCZTMP9qI8pQzejww2Bzq9KBEAhLyfLrqRZmJpHoS8cjq', NULL, NULL, NULL, 'PIMPINAN_FAKULTAS', 'cmoj7qv6p000hot5o7xgokreq', NULL);
INSERT INTO `User` (`id`, `name`, `username`, `password`, `email`, `emailVerified`, `image`, `role`, `facultyId`, `prodiId`) VALUES ('cmojchviq001rot944sznp453', 'Mohamad Sahril, M.Pd.', 'gpm_fkip', '$2b$10$2mHf7sRZxCZTMP9qI8pQzejww2Bzq9KBEAhLyfLrqRZmJpHoS8cjq', NULL, NULL, NULL, 'GPM', 'cmoj7qv6p000hot5o7xgokreq', NULL);
INSERT INTO `User` (`id`, `name`, `username`, `password`, `email`, `emailVerified`, `image`, `role`, `facultyId`, `prodiId`) VALUES ('cmojchvj2001tot944sg5y52w', 'Ilmu Lingkungan', 'ilfts', '$2b$10$2mHf7sRZxCZTMP9qI8pQzejww2Bzq9KBEAhLyfLrqRZmJpHoS8cjq', NULL, NULL, NULL, 'GKM', 'cmoj7qv7x0018ot5orvs72jfk', 'cmoj7qv8h001mot5otn4rjbh5');
INSERT INTO `User` (`id`, `name`, `username`, `password`, `email`, `emailVerified`, `image`, `role`, `facultyId`, `prodiId`) VALUES ('cmojchvje001vot94cilpnm7q', 'Rekayasa Pertanian dan Biosistem', 'rpbfts', '$2b$10$2mHf7sRZxCZTMP9qI8pQzejww2Bzq9KBEAhLyfLrqRZmJpHoS8cjq', NULL, NULL, NULL, 'GKM', 'cmoj7qv7x0018ot5orvs72jfk', 'cmoj7qv8e001kot5o36yhq3ga');
INSERT INTO `User` (`id`, `name`, `username`, `password`, `email`, `emailVerified`, `image`, `role`, `facultyId`, `prodiId`) VALUES ('cmojchvjp001xot94n1lzirfx', 'Sistem Informasi', 'sifts', '$2b$10$2mHf7sRZxCZTMP9qI8pQzejww2Bzq9KBEAhLyfLrqRZmJpHoS8cjq', NULL, NULL, NULL, 'GKM', 'cmoj7qv7x0018ot5orvs72jfk', 'cmoj7qv8b001iot5o9m0fmx4b');
INSERT INTO `User` (`id`, `name`, `username`, `password`, `email`, `emailVerified`, `image`, `role`, `facultyId`, `prodiId`) VALUES ('cmojchvk1001zot94uof8i8fe', 'Teknik Elektro', 'elektro', '$2b$10$2mHf7sRZxCZTMP9qI8pQzejww2Bzq9KBEAhLyfLrqRZmJpHoS8cjq', NULL, NULL, NULL, 'GKM', 'cmoj7qv7x0018ot5orvs72jfk', 'cmoj7qv80001aot5oe3n3iz0b');
INSERT INTO `User` (`id`, `name`, `username`, `password`, `email`, `emailVerified`, `image`, `role`, `facultyId`, `prodiId`) VALUES ('cmojchvkd0021ot942c03epw8', 'Teknik Informatika', 'informatika', '$2b$10$2mHf7sRZxCZTMP9qI8pQzejww2Bzq9KBEAhLyfLrqRZmJpHoS8cjq', NULL, NULL, NULL, 'GKM', 'cmoj7qv7x0018ot5orvs72jfk', 'cmoj7qv83001cot5ow4nhaf44');
INSERT INTO `User` (`id`, `name`, `username`, `password`, `email`, `emailVerified`, `image`, `role`, `facultyId`, `prodiId`) VALUES ('cmojchvkp0023ot94qu6dlagm', 'Teknik Mesin', 'mesin', '$2b$10$2mHf7sRZxCZTMP9qI8pQzejww2Bzq9KBEAhLyfLrqRZmJpHoS8cjq', NULL, NULL, NULL, 'GKM', 'cmoj7qv7x0018ot5orvs72jfk', 'cmoj7qv88001got5opdl6c3zc');
INSERT INTO `User` (`id`, `name`, `username`, `password`, `email`, `emailVerified`, `image`, `role`, `facultyId`, `prodiId`) VALUES ('cmojchvl10025ot94nml73594', 'Teknik Sipil', 'sipil', '$2b$10$2mHf7sRZxCZTMP9qI8pQzejww2Bzq9KBEAhLyfLrqRZmJpHoS8cjq', NULL, NULL, NULL, 'GKM', 'cmoj7qv7x0018ot5orvs72jfk', 'cmoj7qv85001eot5ohn8xcffu');
INSERT INTO `User` (`id`, `name`, `username`, `password`, `email`, `emailVerified`, `image`, `role`, `facultyId`, `prodiId`) VALUES ('cmojchvld0027ot940qsb45pd', 'Dekanat FTS', 'dekanat_fts', '$2b$10$2mHf7sRZxCZTMP9qI8pQzejww2Bzq9KBEAhLyfLrqRZmJpHoS8cjq', NULL, NULL, NULL, 'PIMPINAN_FAKULTAS', 'cmoj7qv7x0018ot5orvs72jfk', NULL);
INSERT INTO `User` (`id`, `name`, `username`, `password`, `email`, `emailVerified`, `image`, `role`, `facultyId`, `prodiId`) VALUES ('cmojchvlp0029ot94chw2sd4z', 'GPM FTS', 'gpm_fts', '$2b$10$2mHf7sRZxCZTMP9qI8pQzejww2Bzq9KBEAhLyfLrqRZmJpHoS8cjq', NULL, NULL, NULL, 'GPM', 'cmoj7qv7x0018ot5orvs72jfk', NULL);
INSERT INTO `User` (`id`, `name`, `username`, `password`, `email`, `emailVerified`, `image`, `role`, `facultyId`, `prodiId`) VALUES ('cmojchvm0002bot94iad0gnr8', 'Magister Ekonomi Syariah', 'esy2_pasca', '$2b$10$2mHf7sRZxCZTMP9qI8pQzejww2Bzq9KBEAhLyfLrqRZmJpHoS8cjq', NULL, NULL, NULL, 'GKM', 'cmoj7qv8t001sot5oueq0h9l7', 'cmoj7qv9b0024ot5osm4l8atw');
INSERT INTO `User` (`id`, `name`, `username`, `password`, `email`, `emailVerified`, `image`, `role`, `facultyId`, `prodiId`) VALUES ('cmojchvmc002dot94btr6gv3c', 'Magister Komunikasi dan Penyiaran Islam', 'kpi2_pasca', '$2b$10$2mHf7sRZxCZTMP9qI8pQzejww2Bzq9KBEAhLyfLrqRZmJpHoS8cjq', NULL, NULL, NULL, 'GKM', 'cmoj7qv8t001sot5oueq0h9l7', 'cmoj7qv950020ot5o49ag5msy');
INSERT INTO `User` (`id`, `name`, `username`, `password`, `email`, `emailVerified`, `image`, `role`, `facultyId`, `prodiId`) VALUES ('cmojchvmp002fot94nxnd3usu', 'Magister Manajemen', 'mm2_pasca', '$2b$10$2mHf7sRZxCZTMP9qI8pQzejww2Bzq9KBEAhLyfLrqRZmJpHoS8cjq', NULL, NULL, NULL, 'GKM', 'cmoj7qv8t001sot5oueq0h9l7', 'cmoj7qv980022ot5o4mjvylyf');
INSERT INTO `User` (`id`, `name`, `username`, `password`, `email`, `emailVerified`, `image`, `role`, `facultyId`, `prodiId`) VALUES ('cmojchvn1002hot94ohkweu7p', 'Magister Pendidikan Agama Islam', 'pai2_pasca', '$2b$10$2mHf7sRZxCZTMP9qI8pQzejww2Bzq9KBEAhLyfLrqRZmJpHoS8cjq', NULL, NULL, NULL, 'GKM', 'cmoj7qv8t001sot5oueq0h9l7', 'cmoj7qv8w001uot5oorvs7yvj');
INSERT INTO `User` (`id`, `name`, `username`, `password`, `email`, `emailVerified`, `image`, `role`, `facultyId`, `prodiId`) VALUES ('cmojchvnd002jot943u10jll1', 'Teknologi Pendidikan (S2)', 'tp2_pasca', '$2b$10$2mHf7sRZxCZTMP9qI8pQzejww2Bzq9KBEAhLyfLrqRZmJpHoS8cjq', NULL, NULL, NULL, 'GKM', 'cmoj7qv8t001sot5oueq0h9l7', 'cmoj7qv92001yot5ov0x12ftr');
INSERT INTO `User` (`id`, `name`, `username`, `password`, `email`, `emailVerified`, `image`, `role`, `facultyId`, `prodiId`) VALUES ('cmojchvnq002lot94ncu85e4j', 'Doktor Ekonomi Syariah', 'esy3_pasca', '$2b$10$2mHf7sRZxCZTMP9qI8pQzejww2Bzq9KBEAhLyfLrqRZmJpHoS8cjq', NULL, NULL, NULL, 'GKM', 'cmoj7qv8t001sot5oueq0h9l7', 'cmoj7qv9e0026ot5o5pf49mmw');
INSERT INTO `User` (`id`, `name`, `username`, `password`, `email`, `emailVerified`, `image`, `role`, `facultyId`, `prodiId`) VALUES ('cmojchvo2002not948nh29ikt', 'Doktor Pendidikan Agama Islam', 'pai3_pasca', '$2b$10$2mHf7sRZxCZTMP9qI8pQzejww2Bzq9KBEAhLyfLrqRZmJpHoS8cjq', NULL, NULL, NULL, 'GKM', 'cmoj7qv8t001sot5oueq0h9l7', 'cmoj7qv90001wot5oxx2kxoef');
INSERT INTO `User` (`id`, `name`, `username`, `password`, `email`, `emailVerified`, `image`, `role`, `facultyId`, `prodiId`) VALUES ('cmojchvoe002pot94ruemrfy3', 'Pimpinan Pasca', 'pasca', '$2b$10$2mHf7sRZxCZTMP9qI8pQzejww2Bzq9KBEAhLyfLrqRZmJpHoS8cjq', NULL, NULL, NULL, 'PIMPINAN_FAKULTAS', 'cmoj7qv8t001sot5oueq0h9l7', NULL);
INSERT INTO `User` (`id`, `name`, `username`, `password`, `email`, `emailVerified`, `image`, `role`, `facultyId`, `prodiId`) VALUES ('cmojchvoq002rot940jmtm6fg', 'Gugus Penjamin Mutu Pasca', 'pgm_pasca', '$2b$10$2mHf7sRZxCZTMP9qI8pQzejww2Bzq9KBEAhLyfLrqRZmJpHoS8cjq', NULL, NULL, NULL, 'GPM', 'cmoj7qv8t001sot5oueq0h9l7', NULL);
INSERT INTO `User` (`id`, `name`, `username`, `password`, `email`, `emailVerified`, `image`, `role`, `facultyId`, `prodiId`) VALUES ('cmojchvp1002tot94zmkefuz1', 'KPMA Admin', 'admin_kpma', '$2b$10$n/U6NDXd6qKDILeALIi3se3mDQtgVI5XVDgb17GjgQeOGBGjU4pK2', NULL, NULL, NULL, 'KPMA', NULL, NULL);
INSERT INTO `User` (`id`, `name`, `username`, `password`, `email`, `emailVerified`, `image`, `role`, `facultyId`, `prodiId`) VALUES ('cmojchvpe002vot94gyfgggyj', 'Kepala KPMA', 'kpma', '$2b$10$2mHf7sRZxCZTMP9qI8pQzejww2Bzq9KBEAhLyfLrqRZmJpHoS8cjq', NULL, NULL, NULL, 'PIMPINAN_UNIVERSITAS', NULL, NULL);
INSERT INTO `User` (`id`, `name`, `username`, `password`, `email`, `emailVerified`, `image`, `role`, `facultyId`, `prodiId`) VALUES ('cmojchvpq002xot94kp5b23r7', 'Rektor', 'rektor', '$2b$10$2mHf7sRZxCZTMP9qI8pQzejww2Bzq9KBEAhLyfLrqRZmJpHoS8cjq', NULL, NULL, NULL, 'PIMPINAN_UNIVERSITAS', NULL, NULL);

-- Data for table `Level`
INSERT INTO `Level` (`id`, `name`) VALUES ('cmojtwmyd0000ot1wjfrqwznd', 'D3');
INSERT INTO `Level` (`id`, `name`) VALUES ('cmojtwmyw0001ot1wd1r0w879', 'D4');
INSERT INTO `Level` (`id`, `name`) VALUES ('cmojtwmz20002ot1w99j3mn9s', 'S1');
INSERT INTO `Level` (`id`, `name`) VALUES ('cmojtwmz80003ot1wn99jhwfy', 'S2');
INSERT INTO `Level` (`id`, `name`) VALUES ('cmojtwmzd0004ot1wz1da2e0y', 'S3');
INSERT INTO `Level` (`id`, `name`) VALUES ('cmojzqh8q0000otlgbpxn4lu6', 'S1 Profesi');

-- Data for table `Setting`
INSERT INTO `Setting` (`id`, `appscript_url`) VALUES ('cmnmq11tl0000uiyoagns994y', 'https://script.google.com/macros/s/AKfycbwXlaVGR0odoRtu-F1aVWQPmcasUu_sfYNxel7i4Z_EBRFWGfUBTdQve-ziFm5Mit4t/exec');

-- Data for table `Cycle`
INSERT INTO `Cycle` (`id`, `tahun_akademik`, `semester`, `isActive`) VALUES ('cmoi7ecde0000otese6iy4cid', '2025/2026', 'Ganjil', 1);

-- Data for table `Document`
INSERT INTO `Document` (`id`, `type`, `title`, `description`, `fileUrl`, `createdAt`) VALUES ('cmok2l7oa0000otds8koac3s6', 'PERATURAN', 'SK Pelaksanaan AMI UIKA Bogor', 'SK Rektor No. 287 Tentang Pelaksanaan AMI dan Monev 2 Kali', 'https://drive.google.com/file/d/14M4nuYbluqDYPLMgsYJ_USO6Fg5MKkSl/view?usp=drivesdk', '2026-04-29 13:07:38');
INSERT INTO `Document` (`id`, `type`, `title`, `description`, `fileUrl`, `createdAt`) VALUES ('cmok2o2tv0001otdsjselmap6', 'INSTRUMEN', 'Panduan Pengisian Prodi Doktor', 'Panduan Pengisian Intrumen Monev untuk Program Studi Doktor', 'https://drive.google.com/file/d/1RkhSKX2vHOC2TmFXYV4HLM6YKSXKk9U4/view?usp=drivesdk', '2026-04-29 13:09:52');
INSERT INTO `Document` (`id`, `type`, `title`, `description`, `fileUrl`, `createdAt`) VALUES ('cmok2oq5i0002otdstu2vrim0', 'INSTRUMEN', 'Panduan Pengisian Prodi Magister', 'Panduan Pengisian Intrumen Monev untuk Program Studi Magister', 'https://drive.google.com/file/d/1d_jWMgP9scW9kMwgd3tJWB3QvEFEO_Le/view?usp=drivesdk', '2026-04-29 13:10:22');
INSERT INTO `Document` (`id`, `type`, `title`, `description`, `fileUrl`, `createdAt`) VALUES ('cmok2p9dr0003otdskb9alsri', 'INSTRUMEN', 'Panduan Pengisian Prodi Sarjana', 'Panduan Pengisian Intrumen Monev untuk Program Studi Sarjana', 'https://drive.google.com/file/d/1drgJSDV7Jfg8lnSJywVp_dFR0zmZn19D/view?usp=drivesdk', '2026-04-29 13:10:47');
INSERT INTO `Document` (`id`, `type`, `title`, `description`, `fileUrl`, `createdAt`) VALUES ('cmok2q1wl0004otds76kba69i', 'INSTRUMEN', 'Contoh Pengisian Monev Prodi Sarjana', 'Contoh Pengisian Intrumen Monev Program Studi Sarjana', 'https://drive.google.com/file/d/1j1pgaVXcJG3EgzZ0w6IXJzEVvq_0H5ao/view?usp=drivesdk', '2026-04-29 13:11:24');
INSERT INTO `Document` (`id`, `type`, `title`, `description`, `fileUrl`, `createdAt`) VALUES ('cmok2quyi0005otds27hysa8t', 'INSTRUMEN', 'Contoh Pengisian Monev Prodi Magister', 'Contoh pengisian intrumen monev program studi magister', 'https://drive.google.com/file/d/1eSfJuoCtR_DJwWXNFEqstZNOglguWRUJ/view?usp=drivesdk', '2026-04-29 13:12:02');
INSERT INTO `Document` (`id`, `type`, `title`, `description`, `fileUrl`, `createdAt`) VALUES ('cmok2riq70006otds9k5d1vwx', 'INSTRUMEN', 'Contoh Pengisian Monev Prodi Doktor', 'Contoh pengisian intrumen monev program studi doktor', 'https://drive.google.com/file/d/1Q9n4yWpYm0vxX5tAmrvWozKeFeezffVq/view?usp=drivesdk', '2026-04-29 13:12:32');

-- Data for table `Faculty`
INSERT INTO `Faculty` (`id`, `name`) VALUES ('cmoj7qv5y0000ot5occuyj350', 'Fakultas Agama Islam');
INSERT INTO `Faculty` (`id`, `name`) VALUES ('cmoj7qv6p000hot5o7xgokreq', 'Fakultas Keguruan dan Ilmu Pendidikan');
INSERT INTO `Faculty` (`id`, `name`) VALUES ('cmoj7qv77000sot5oor0zjdjz', 'Fakultas Ekonomi dan Bisnis');
INSERT INTO `Faculty` (`id`, `name`) VALUES ('cmoj7qv7o0013ot5ocepb6wzd', 'Fakultas Hukum');
INSERT INTO `Faculty` (`id`, `name`) VALUES ('cmoj7qv7x0018ot5orvs72jfk', 'Fakultas Teknik dan Sains');
INSERT INTO `Faculty` (`id`, `name`) VALUES ('cmoj7qv8k001not5on41vuh1a', 'Fakultas Ilmu Kesehatan');
INSERT INTO `Faculty` (`id`, `name`) VALUES ('cmoj7qv8t001sot5oueq0h9l7', 'Sekolah Pascasarjana');

-- Data for table `Prodi`
INSERT INTO `Prodi` (`id`, `facultyId`, `name`, `jenjang`) VALUES ('cmoj7qv620002ot5oxtfoxsxd', 'cmoj7qv5y0000ot5occuyj350', 'Pendidikan Agama Islam', 'S1');
INSERT INTO `Prodi` (`id`, `facultyId`, `name`, `jenjang`) VALUES ('cmoj7qv650004ot5oi5fjswyx', 'cmoj7qv5y0000ot5occuyj350', 'Pendidikan Guru Madrasah Ibtidaiyah', 'S1');
INSERT INTO `Prodi` (`id`, `facultyId`, `name`, `jenjang`) VALUES ('cmoj7qv680006ot5ool6isbco', 'cmoj7qv5y0000ot5occuyj350', 'Ekonomi Syariah', 'S1');
INSERT INTO `Prodi` (`id`, `facultyId`, `name`, `jenjang`) VALUES ('cmoj7qv6b0008ot5ob31efhe0', 'cmoj7qv5y0000ot5occuyj350', 'Hukum Keluarga Islam', 'S1');
INSERT INTO `Prodi` (`id`, `facultyId`, `name`, `jenjang`) VALUES ('cmoj7qv6e000aot5obu0a6otd', 'cmoj7qv5y0000ot5occuyj350', 'Ilmu Al Quran dan Tafsir', 'S1');
INSERT INTO `Prodi` (`id`, `facultyId`, `name`, `jenjang`) VALUES ('cmoj7qv6h000cot5o9vzhbsuq', 'cmoj7qv5y0000ot5occuyj350', 'Manajemen Haji dan Umrah', 'S1');
INSERT INTO `Prodi` (`id`, `facultyId`, `name`, `jenjang`) VALUES ('cmoj7qv6j000eot5o8oiezdnp', 'cmoj7qv5y0000ot5occuyj350', 'Bimbingan dan Konseling Pendidikan Islam', 'S1');
INSERT INTO `Prodi` (`id`, `facultyId`, `name`, `jenjang`) VALUES ('cmoj7qv6m000got5olmqf5wpx', 'cmoj7qv5y0000ot5occuyj350', 'Komunikasi dan Penyiaran Islam', 'S1');
INSERT INTO `Prodi` (`id`, `facultyId`, `name`, `jenjang`) VALUES ('cmoj7qv6t000jot5o0xxsc6vx', 'cmoj7qv6p000hot5o7xgokreq', 'Pendidikan Bahasa Inggris', 'S1');
INSERT INTO `Prodi` (`id`, `facultyId`, `name`, `jenjang`) VALUES ('cmoj7qv6w000lot5o1tywnh6y', 'cmoj7qv6p000hot5o7xgokreq', 'Pendidikan Masyarakat', 'S1');
INSERT INTO `Prodi` (`id`, `facultyId`, `name`, `jenjang`) VALUES ('cmoj7qv6z000not5oqpc6c218', 'cmoj7qv6p000hot5o7xgokreq', 'Pendidikan Matematika', 'S1');
INSERT INTO `Prodi` (`id`, `facultyId`, `name`, `jenjang`) VALUES ('cmoj7qv72000pot5ou2eqq7uo', 'cmoj7qv6p000hot5o7xgokreq', 'Pendidikan Vokasional Desain Fashion', 'S1');
INSERT INTO `Prodi` (`id`, `facultyId`, `name`, `jenjang`) VALUES ('cmoj7qv74000rot5oa1ml9jfr', 'cmoj7qv6p000hot5o7xgokreq', 'Tekonologi Pendidikan', 'S1');
INSERT INTO `Prodi` (`id`, `facultyId`, `name`, `jenjang`) VALUES ('cmoj7qv7a000uot5ormt5ecrc', 'cmoj7qv77000sot5oor0zjdjz', 'Akuntansi', 'S1');
INSERT INTO `Prodi` (`id`, `facultyId`, `name`, `jenjang`) VALUES ('cmoj7qv7d000wot5oo85x7jee', 'cmoj7qv77000sot5oor0zjdjz', 'Manajemen', 'S1');
INSERT INTO `Prodi` (`id`, `facultyId`, `name`, `jenjang`) VALUES ('cmoj7qv7f000yot5ot7aa4g10', 'cmoj7qv77000sot5oor0zjdjz', 'Perdagangan Internasional', 'S1');
INSERT INTO `Prodi` (`id`, `facultyId`, `name`, `jenjang`) VALUES ('cmoj7qv7i0010ot5oe18c2p65', 'cmoj7qv77000sot5oor0zjdjz', 'Bisnis Digital', 'S1');
INSERT INTO `Prodi` (`id`, `facultyId`, `name`, `jenjang`) VALUES ('cmoj7qv7l0012ot5o02rbjsr9', 'cmoj7qv77000sot5oor0zjdjz', 'Perbankan dan Keuangan Digital', 'D4');
INSERT INTO `Prodi` (`id`, `facultyId`, `name`, `jenjang`) VALUES ('cmoj7qv7r0015ot5oo685f5us', 'cmoj7qv7o0013ot5ocepb6wzd', 'Ilmu Hukum', 'S1');
INSERT INTO `Prodi` (`id`, `facultyId`, `name`, `jenjang`) VALUES ('cmoj7qv7u0017ot5o0r0ysdau', 'cmoj7qv7o0013ot5ocepb6wzd', 'Hukum Bisnis', 'S2');
INSERT INTO `Prodi` (`id`, `facultyId`, `name`, `jenjang`) VALUES ('cmoj7qv80001aot5oe3n3iz0b', 'cmoj7qv7x0018ot5orvs72jfk', 'Teknik Elektro', 'S1');
INSERT INTO `Prodi` (`id`, `facultyId`, `name`, `jenjang`) VALUES ('cmoj7qv83001cot5ow4nhaf44', 'cmoj7qv7x0018ot5orvs72jfk', 'Teknik Informatika', 'S1');
INSERT INTO `Prodi` (`id`, `facultyId`, `name`, `jenjang`) VALUES ('cmoj7qv85001eot5ohn8xcffu', 'cmoj7qv7x0018ot5orvs72jfk', 'Teknik Sipil', 'S1');
INSERT INTO `Prodi` (`id`, `facultyId`, `name`, `jenjang`) VALUES ('cmoj7qv88001got5opdl6c3zc', 'cmoj7qv7x0018ot5orvs72jfk', 'Teknik Mesin', 'S1');
INSERT INTO `Prodi` (`id`, `facultyId`, `name`, `jenjang`) VALUES ('cmoj7qv8b001iot5o9m0fmx4b', 'cmoj7qv7x0018ot5orvs72jfk', 'Sistem Informasi', 'S1');
INSERT INTO `Prodi` (`id`, `facultyId`, `name`, `jenjang`) VALUES ('cmoj7qv8e001kot5o36yhq3ga', 'cmoj7qv7x0018ot5orvs72jfk', 'Rekayasa Pertanian Dan Biosistem', 'S1');
INSERT INTO `Prodi` (`id`, `facultyId`, `name`, `jenjang`) VALUES ('cmoj7qv8h001mot5otn4rjbh5', 'cmoj7qv7x0018ot5orvs72jfk', 'Ilmu Lingkungan', 'S1');
INSERT INTO `Prodi` (`id`, `facultyId`, `name`, `jenjang`) VALUES ('cmoj7qv8n001pot5onhv18sh6', 'cmoj7qv8k001not5on41vuh1a', 'Kesehatan Masyarakat', 'S1');
INSERT INTO `Prodi` (`id`, `facultyId`, `name`, `jenjang`) VALUES ('cmoj7qv8q001rot5o633hdgl4', 'cmoj7qv8k001not5on41vuh1a', 'Gizi', 'S1');
INSERT INTO `Prodi` (`id`, `facultyId`, `name`, `jenjang`) VALUES ('cmoj7qv8w001uot5oorvs7yvj', 'cmoj7qv8t001sot5oueq0h9l7', 'Pendidikan Agama Islam', 'S2');
INSERT INTO `Prodi` (`id`, `facultyId`, `name`, `jenjang`) VALUES ('cmoj7qv90001wot5oxx2kxoef', 'cmoj7qv8t001sot5oueq0h9l7', 'Pendidikan Agama Islam', 'S3');
INSERT INTO `Prodi` (`id`, `facultyId`, `name`, `jenjang`) VALUES ('cmoj7qv92001yot5ov0x12ftr', 'cmoj7qv8t001sot5oueq0h9l7', 'Teknologi Pendidikan', 'S2');
INSERT INTO `Prodi` (`id`, `facultyId`, `name`, `jenjang`) VALUES ('cmoj7qv950020ot5o49ag5msy', 'cmoj7qv8t001sot5oueq0h9l7', 'Komunikasi dan Penyiaran Islam', 'S2');
INSERT INTO `Prodi` (`id`, `facultyId`, `name`, `jenjang`) VALUES ('cmoj7qv980022ot5o4mjvylyf', 'cmoj7qv8t001sot5oueq0h9l7', 'Manajemen', 'S2');
INSERT INTO `Prodi` (`id`, `facultyId`, `name`, `jenjang`) VALUES ('cmoj7qv9b0024ot5osm4l8atw', 'cmoj7qv8t001sot5oueq0h9l7', 'Ekonomi Syariah', 'S2');
INSERT INTO `Prodi` (`id`, `facultyId`, `name`, `jenjang`) VALUES ('cmoj7qv9e0026ot5o5pf49mmw', 'cmoj7qv8t001sot5oueq0h9l7', 'Ekonomi Syariah', 'S3');

-- Data for table `Instrument`
INSERT INTO `Instrument` (`id`, `category`, `name`, `kriteria`, `indikator`, `jenjang_peruntukan`, `questions`) VALUES ('BM-1', 'Budaya Mutu', 'SPMI – Standar & Tata Kelola', '-', '-', 'Semua', '[{"id":"q1","text":"Apakah Program Studi memiliki Standar Pendidikan Tinggi yang melampaui SN Dikti dan berorientasi akademik?","bobot":0},{"id":"q2","text":"Apakah terdapat panduan dan prosedur implementasi SPMI (penyusunan kurikulum berbasis KKNI level 6, panduan pengajaran dan pembelajaran, panduan penilaian mahasiswa)?","bobot":0},{"id":"q3","text":"Apakah tata kelola SPMI bersifat akuntabel dan transparan serta diimplementasikan secara konsisten minimal 3 tahun?","bobot":0},{"id":"q4","text":"Apakah terdapat panduan/prosedur/sistem yang menunjukkan keberfungsian penjaminan mutu di tingkat program studi?","bobot":0},{"id":"q5","text":"Apakah Sistem Evaluasi Pemenuhan Standar Pendidikan Tinggi dilaksanakan secara transparan, akuntabel, dan mapan minimal 3 tahun?","bobot":0},{"id":"q6","text":"Apakah Sistem Peningkatan Mutu Program Studi secara berkelanjutan telah diimplementasikan secara efektif dan efisien minimal 3 tahun?","bobot":0},{"id":"q7","text":"Apakah implementasi SPMI terbukti efektif dalam peningkatan mutu pendidikan secara berkelanjutan? (Syarat Perlu Terakreditasi Unggul)","bobot":0}]');
INSERT INTO `Instrument` (`id`, `category`, `name`, `kriteria`, `indikator`, `jenjang_peruntukan`, `questions`) VALUES ('BM-2', 'Budaya Mutu', 'Siklus PPEPP pada Kurikulum', '-', '-', 'Semua', '[{"id":"q1","text":"Apakah terdapat proses perencanaan kegiatan pendidikan dan pembelajaran?","bobot":0},{"id":"q2","text":"Apakah terdapat bukti pelaksanaan kegiatan pendidikan dan pembelajaran sesuai standar?","bobot":0},{"id":"q3","text":"Apakah evaluasi hasil pembelajaran mahasiswa dilaksanakan secara sistematis?","bobot":0},{"id":"q4","text":"Apakah asesmen CPL dan luaran program studi dilakukan secara berkala?","bobot":0},{"id":"q5","text":"Apakah evaluasi hasil asesmen dilakukan dan terdokumentasi?","bobot":0},{"id":"q6","text":"Apakah terdapat analisis dan evaluasi masukan dari pemangku kepentingan?","bobot":0},{"id":"q7","text":"Apakah hasil evaluasi digunakan sebagai umpan balik untuk pengembangan matakuliah dan kurikulum?","bobot":0},{"id":"q8","text":"Apakah siklus PPEPP berjalan konsisten, efektif, dan berkelanjutan? (Syarat Perlu Terakreditasi Unggul)","bobot":0}]');
INSERT INTO `Instrument` (`id`, `category`, `name`, `kriteria`, `indikator`, `jenjang_peruntukan`, `questions`) VALUES ('BM-3', 'Budaya Mutu', 'Laporan SPMI & PD Dikti', '-', '-', 'Semua', '[{"id":"q1","text":"Apakah terdapat laporan semesteran/tahunan implementasi SPMI secara berkala dan lengkap dalam 3 tahun terakhir?","bobot":0},{"id":"q2","text":"Apakah terdapat laporan Audit Mutu Internal (AMI) yang lengkap?","bobot":0},{"id":"q3","text":"Apakah kinerja program studi tercermin dalam laporan dan menunjukkan perbaikan yang menerus?","bobot":0},{"id":"q4","text":"Apakah sistem pengelolaan data melalui PD Dikti berjalan transparan, akuntabel, valid, dan berintegritas?","bobot":0},{"id":"q5","text":"Apakah data PD Dikti dimutakhirkan secara berkala setiap semester?","bobot":0}]');
INSERT INTO `Instrument` (`id`, `category`, `name`, `kriteria`, `indikator`, `jenjang_peruntukan`, `questions`) VALUES ('BM-4', 'Budaya Mutu', 'Pengakuan Efektivitas SPMI', '-', '-', 'Semua', '[{"id":"q1","text":"Apakah Program Studi memiliki status Akreditasi dari BAN-PT/LAM?","bobot":0},{"id":"q2","text":"Apakah tingkat kepuasan pemangku kepentingan terhadap lulusan Prodi pada TS-2 > 75%?","bobot":0},{"id":"q3","text":"Apakah Hasil AMI dalam 2 tahun terakhir memiliki skor rata-rata > 75%? (untuk Prodi Terakreditasi Pertama)","bobot":0},{"id":"q4","text":"Apakah terdapat pengakuan mutu lain dari pihak eksternal? (Syarat Perlu Terakreditasi Unggul)","bobot":0}]');
INSERT INTO `Instrument` (`id`, `category`, `name`, `kriteria`, `indikator`, `jenjang_peruntukan`, `questions`) VALUES ('BM-01', 'Budaya Mutu', 'SPMI - Standar & Tata Kelola', '-', '-', 'S2', '[{"id":"q1","text":"Apakah Program Studi memiliki Standar Pendidikan Tinggi yang melampaui SN Dikti dan berorientasi akademik serta pendalaman dan pengembangan ilmu pengetahuan?","bobot":0},{"id":"q2","text":"Apakah terdapat panduan dan prosedur implementasi SPMI (penyusunan kurikulum berbasis KKNI level 8, panduan pengajaran dan pembelajaran, panduan penilaian mahasiswa)?","bobot":0},{"id":"q3","text":"Apakah tata kelola SPMI bersifat akuntabel dan transparan serta diimplementasikan secara konsisten minimal 3 tahun?","bobot":0},{"id":"q4","text":"Apakah terdapat panduan/prosedur/sistem yang menunjukkan keberfungsian penjaminan mutu di tingkat program studi?","bobot":0},{"id":"q5","text":"Apakah Sistem Evaluasi Pemenuhan Standar Pendidikan Tinggi dilaksanakan secara transparan, akuntabel, dan mapan minimal 3 tahun?","bobot":0},{"id":"q6","text":"Apakah Sistem Peningkatan Mutu Program Studi secara berkelanjutan telah diimplementasikan secara efektif dan efisien minimal 3 tahun?","bobot":0},{"id":"q7","text":"Apakah implementasi SPMI terbukti efektif dalam peningkatan mutu pendidikan secara berkelanjutan? (Syarat Perlu Terakreditasi Unggul)","bobot":0}]');
INSERT INTO `Instrument` (`id`, `category`, `name`, `kriteria`, `indikator`, `jenjang_peruntukan`, `questions`) VALUES ('BM-001', 'Budaya Mutu', 'SPMI - Standar & Tata Kelola', '-', '-', 'S3', '[{"id":"q1","text":"Apakah Program Studi memiliki Standar Pendidikan Tinggi yang melampaui SN Dikti dan berorientasi akademik serta pengembangan ilmu pengetahuan baru?","bobot":0},{"id":"q2","text":"Apakah terdapat panduan dan prosedur implementasi SPMI di Program Studi (penyusunan kurikulum berbasis KKNI level 9, panduan pengajaran berbasis riset, panduan penilaian mahasiswa)?","bobot":0},{"id":"q3","text":"Apakah tata kelola SPMI bersifat akuntabel dan transparan serta telah diimplementasikan secara konsisten minimal selama 3 tahun?","bobot":0},{"id":"q4","text":"Apakah terdapat panduan/prosedur/sistem yang menunjukkan keberfungsian penjaminan mutu di tingkat program studi?","bobot":0},{"id":"q5","text":"Apakah Sistem Evaluasi Pemenuhan Standar Pendidikan Tinggi dilaksanakan secara transparan, akuntabel, dan mapan minimal 3 tahun?","bobot":0},{"id":"q6","text":"Apakah Sistem Peningkatan Mutu Program Studi secara berkelanjutan telah diimplementasikan secara efektif dan efisien minimal 3 tahun?","bobot":0},{"id":"q7","text":"Apakah implementasi SPMI terbukti efektif dalam peningkatan mutu pendidikan secara berkelanjutan (Syarat Perlu Terakreditasi Unggul)?","bobot":0}]');
INSERT INTO `Instrument` (`id`, `category`, `name`, `kriteria`, `indikator`, `jenjang_peruntukan`, `questions`) VALUES ('RP-5', 'Relevansi Pendidikan', 'Kurikulum Program Studi', '-', '-', 'S1', '[{"id":"q1","text":"Apakah terdapat dokumen kurikulum yang lengkap mencakup: keunikan program studi?","bobot":0},{"id":"q2","text":"Apakah profil lulusan didefinisikan secara jelas dalam dokumen kurikulum?","bobot":0},{"id":"q3","text":"Apakah Capaian Pembelajaran Lulusan (CPL) sesuai dengan KKNI level 6?","bobot":0},{"id":"q4","text":"Apakah struktur kurikulum terdokumentasi dan dipublikasikan?","bobot":0},{"id":"q5","text":"Apakah silabus matakuliah tersedia dan mutakhir?","bobot":0},{"id":"q6","text":"Apakah Rencana Pembelajaran Semester (RPS) tersedia untuk semua matakuliah?","bobot":0},{"id":"q7","text":"Apakah evaluasi kurikulum melibatkan pemangku kepentingan internal dan eksternal (DUDIK)?","bobot":0},{"id":"q8","text":"Apakah kurikulum disesuaikan dengan kebijakan pemerintah dan perkembangan IPTEK?","bobot":0}]');
INSERT INTO `Instrument` (`id`, `category`, `name`, `kriteria`, `indikator`, `jenjang_peruntukan`, `questions`) VALUES ('RP-05', 'Relevansi Pendidikan', 'Kurikulum Program Studi', '-', '-', 'S2', '[{"id":"q1","text":"Apakah terdapat dokumen kurikulum yang lengkap mencakup: keunikan program studi?","bobot":0},{"id":"q2","text":"Apakah profil lulusan didefinisikan secara jelas dalam dokumen kurikulum?","bobot":0},{"id":"q3","text":"Apakah Capaian Pembelajaran Lulusan (CPL) sesuai dengan KKNI level 8?","bobot":0},{"id":"q4","text":"Apakah struktur kurikulum terdokumentasi dan dipublikasikan?","bobot":0},{"id":"q5","text":"Apakah silabus matakuliah tersedia dan mutakhir?","bobot":0},{"id":"q6","text":"Apakah Rencana Pembelajaran Semester (RPS) tersedia untuk semua matakuliah?","bobot":0},{"id":"q7","text":"Apakah evaluasi kurikulum melibatkan pemangku kepentingan internal dan eksternal (DUDIK)?","bobot":0},{"id":"q8","text":"Apakah kurikulum disesuaikan dengan kebijakan pemerintah dan perkembangan IPTEK?","bobot":0}]');
INSERT INTO `Instrument` (`id`, `category`, `name`, `kriteria`, `indikator`, `jenjang_peruntukan`, `questions`) VALUES ('RP-005', 'Relevansi Pendidikan', 'Kurikulum Program Studi', '-', '-', 'S3', '[{"id":"q1","text":"Apakah terdapat dokumen kurikulum yang lengkap mencakup: keunikan program studi?","bobot":0},{"id":"q2","text":"Apakah profil lulusan didefinisikan secara jelas dalam dokumen kurikulum?","bobot":0},{"id":"q3","text":"Apakah Capaian Pembelajaran Lulusan (CPL) sesuai dengan KKNI level 9?","bobot":0},{"id":"q4","text":"Apakah struktur kurikulum terdokumentasi dan dipublikasikan?","bobot":0},{"id":"q5","text":"Apakah silabus matakuliah tersedia dan mutakhir?","bobot":0},{"id":"q6","text":"Apakah Rencana Pembelajaran Semester (RPS) tersedia untuk semua matakuliah?","bobot":0},{"id":"q7","text":"Apakah evaluasi kurikulum melibatkan pemangku kepentingan internal dan eksternal (DUDIK)?","bobot":0},{"id":"q8","text":"Apakah kurikulum disesuaikan dengan kebijakan pemerintah dan perkembangan IPTEK?","bobot":0}]');
INSERT INTO `Instrument` (`id`, `category`, `name`, `kriteria`, `indikator`, `jenjang_peruntukan`, `questions`) VALUES ('RP-6-S1', 'Relevansi Pendidikan', 'Kompetensi & Kualifikasi DPR', '-', '-', 'S1', '[{"id":"q1","text":"Apakah DPR memiliki kompetensi pedagogik, kepribadian, sosial, dan profesional?","bobot":0},{"id":"q2","text":"Apakah kualifikasi DPR minimal lulusan Magister (S2) dengan bidang keahlian sesuai matakuliah? (Kualifikasi Doktor minimal mencapai 25% dari total DPR)","bobot":0},{"id":"q3","text":"Apakah UPPS menetapkan sasaran strategis terkait profesi dan karir dosen?","bobot":0},{"id":"q4","text":"Apakah kesesuaian bidang keahlian dosen dengan matakuliah yang diampu terdokumentasi?","bobot":0},{"id":"q5","text":"Apakah luaran dosen mendukung diferensiasi misi UPPS? (publikasi jurnal, buku ajar, inovasi riset, produk PkM)","bobot":0},{"id":"q6","text":"Apakah Program Studi memiliki sekurang-kurangnya 9 orang DPR dengan kualifikasi Doktor minimal 25% dari seluruh DPR? (LKPS Tabel 2-I.1)","bobot":0},{"id":"q7","text":"Apakah DPR dalam jabatan akademik Guru Besar, Lektor Kepala, atau Lektor dengan PDJA >= 80%? (tidak termasuk Asisten Ahli)","bobot":0},{"id":"q8","text":"Apakah persentase Dosen Tidak Tetap (PDTT) <= 10%? (LKPS Tabel 2-I.2)","bobot":0},{"id":"q9","text":"Apakah beban kerja DPR (EWMP) berada pada rentang 12-16 sks? (LKPS Tabel 2-I.3)","bobot":0}]');
INSERT INTO `Instrument` (`id`, `category`, `name`, `kriteria`, `indikator`, `jenjang_peruntukan`, `questions`) VALUES ('RP-6-S2', 'Relevansi Pendidikan', 'Kompetensi & Kualifikasi DPR', '-', '-', 'S2', '[{"id":"q1","text":"Apakah DPR memiliki kompetensi pedagogik, kepribadian, sosial, dan profesional?","bobot":0},{"id":"q2","text":"Apakah kualifikasi DPR minimal lulusan Doktor dengan bidang keahlian sesuai matakuliah? Catatan: Kualifikasi pendidikan Doktor minimal mencapai 25% dari total DPR di PD Dikti","bobot":0},{"id":"q3","text":"Apakah UPPS menetapkan sasaran strategis terkait profesi dan karir dosen?","bobot":0},{"id":"q4","text":"Apakah kesesuaian bidang keahlian dosen dengan matakuliah yang diampu terdokumentasi?","bobot":0},{"id":"q5","text":"Apakah luaran dosen mendukung diferensiasi misi UPPS? (publikasi di jurnal pendidikan/riset bereputasi, buku ajar, inovasi riset, atau produk PkM)","bobot":0},{"id":"q6","text":"Apakah Program Studi memiliki sekurang-kurangnya 7 orang DPR dengan kualifikasi Doktor yang relevan? (LKPS Tabel 2-I.1)","bobot":0},{"id":"q7","text":"Apakah DPR dalam jabatan akademik Guru Besar, Lektor Kepala, atau Lektor dengan PDJA >= 80%? (tidak termasuk Asisten Ahli)","bobot":0},{"id":"q8","text":"Apakah persentase Dosen Tidak Tetap (PDTT) <= 10%? (LKPS Tabel 2-I.2)","bobot":0},{"id":"q9","text":"Apakah beban kerja DPR (EWMP) berada pada rentang 12-16 sks? (LKPS Tabel 2-I.3)","bobot":0}]');
INSERT INTO `Instrument` (`id`, `category`, `name`, `kriteria`, `indikator`, `jenjang_peruntukan`, `questions`) VALUES ('RP-6-S3', 'Relevansi Pendidikan', 'Kompetensi & Kualifikasi DPR', '-', '-', 'S3', '[{"id":"q1","text":"Apakah DPR memiliki kompetensi pedagogik, kepribadian, sosial, dan profesional?","bobot":0},{"id":"q2","text":"Apakah kualifikasi DPR minimal lulusan doktor dengan bidang keahlian sesuai matakuliah?","bobot":0},{"id":"q3","text":"Apakah UPPS menetapkan sasaran strategis terkait profesi dan karir dosen?","bobot":0},{"id":"q4","text":"Apakah DPR produktif menghasilkan minimal 3 karya akademik/inovatif nasional sebagai penulis/pelaksana pertama?","bobot":0},{"id":"q5","text":"Apakah Program Studi memiliki sekurang-kurangnya 7 orang DPR dengan kualifikasi Doktor yang relevan? (LKPS Tabel 2-I.1)","bobot":0},{"id":"q6","text":"Apakah DPR dalam jabatan akademik Guru Besar (PDJA >= 5)? (Syarat Perlu Terakreditasi Unggul)","bobot":0},{"id":"q7","text":"Apakah persentase Dosen Tidak Tetap (PDTT) <= 10%? (LKPS Tabel 2-I.2)","bobot":0},{"id":"q8","text":"Apakah beban kerja DPR (EWMP) berada pada rentang 12-16 sks? (LKPS Tabel 2-I.3)","bobot":0},{"id":"q9","text":"Apakah kesesuaian keahlian DPR dengan kompetensi inti program studi >= 90%?","bobot":0}]');
INSERT INTO `Instrument` (`id`, `category`, `name`, `kriteria`, `indikator`, `jenjang_peruntukan`, `questions`) VALUES ('RP-7', 'Relevansi Pendidikan', 'Kecukupan Tenaga Kependidikan', '-', '-', 'Semua', '[{"id":"q1","text":"Apakah tenaga kependidikan memiliki kompetensi yang mendukung tugas pokok layanan akademik, administrasi, dan IT?","bobot":0},{"id":"q2","text":"Apakah kualifikasi pendidikan tenaga kependidikan minimal Diploma Tiga (D-3)?","bobot":0},{"id":"q3","text":"Apakah tenaga kependidikan bekerja penuh waktu (37.5 jam/minggu)?","bobot":0},{"id":"q4","text":"Apakah jumlah tenaga kependidikan memenuhi tingkat kecukupan kebutuhan layanan program studi?","bobot":0},{"id":"q5","text":"Apakah terdapat tenaga kependidikan yang memiliki sertifikasi pelatihan relevan?","bobot":0}]');
INSERT INTO `Instrument` (`id`, `category`, `name`, `kriteria`, `indikator`, `jenjang_peruntukan`, `questions`) VALUES ('RP-8', 'Sarana, Prasarana, Pembiayaan & K3', 'Sarana, Prasarana, Pembiayaan & K3', '-', '-', 'Semua', '[{"id":"q1","text":"Apakah UPPS menjamin akses sarana dan prasarana yang mengakomodasi kebutuhan mahasiswa, dosen, dan tendik?","bobot":0},{"id":"q2","text":"Apakah sarana prasarana ramah terhadap mahasiswa/dosen/tendik berkebutuhan khusus?","bobot":0},{"id":"q3","text":"Apakah tersedia TIK yang andal untuk mendukung pendidikan?","bobot":0},{"id":"q4","text":"Apakah sarana dan prasarana mendukung fokus diferensiasi misi UPPS (lab riset/lab pendidikan/lab inovasi)?","bobot":0},{"id":"q5","text":"Apakah tersedia sistem K3 terkait keamanan, keselamatan, dan kesehatan?","bobot":0},{"id":"q6","text":"Apakah terdapat kelengkapan pencegahan dan pemadaman kebakaran serta penanggulangan bencana?","bobot":0},{"id":"q7","text":"Apakah tersedia sistem pengelolaan sampah dan limbah B3?","bobot":0},{"id":"q8","text":"Apakah fasilitas memenuhi standar kesehatan kerja dan lingkungan kerja yang sehat?","bobot":0},{"id":"q9","text":"Apakah kampus merupakan Kawasan Tanpa Rokok dan bebas NAPZA?","bobot":0},{"id":"q10","text":"Apakah biaya investasi > 5% dari total anggaran? (LKPS Tabel 2-I.5)","bobot":0},{"id":"q11","text":"Apakah biaya operasional pendidikan rata-rata >= Rp15 juta per mahasiswa aktif per tahun?","bobot":0}]');
INSERT INTO `Instrument` (`id`, `category`, `name`, `kriteria`, `indikator`, `jenjang_peruntukan`, `questions`) VALUES ('RP-9', 'Relevansi Pendidikan', 'Sistem TIK Pendukung Pendidikan', '-', '-', 'Semua', '[{"id":"q1","text":"Apakah sistem TIK mendukung pengembangan materi dan pelaksanaan pembelajaran/ujian?","bobot":0},{"id":"q2","text":"Apakah TIK memastikan keamanan, kebenaran, akurasi, dan kemutakhiran data akademik?","bobot":0},{"id":"q3","text":"Apakah TIK mendukung perencanaan, pelaksanaan, pengawasan, dan pengambilan keputusan?","bobot":0},{"id":"q4","text":"Apakah data profil dan kinerja prodi dilaporkan ke PD Dikti secara rutin?","bobot":0},{"id":"q5","text":"Apakah data dan informasi perguruan tinggi dapat diakses publik?","bobot":0},{"id":"q6","text":"Apakah sistem TIK menunjang fokus diferensiasi misi PT?","bobot":0},{"id":"q7","text":"Apakah sistem TIK dievaluasi secara periodik dan ditindaklanjuti?","bobot":0}]');
INSERT INTO `Instrument` (`id`, `category`, `name`, `kriteria`, `indikator`, `jenjang_peruntukan`, `questions`) VALUES ('RP-10-S1', 'Relevansi Pendidikan', 'Standar & Fleksibilitas Proses Pembelajaran', '-', '-', 'S1', '[{"id":"q1","text":"Apakah standar perencanaan proses pembelajaran mencakup: perumusan CPL, strategi/metode pembelajaran, dan cara penilaian?","bobot":0},{"id":"q2","text":"Apakah pelaksanaan pembelajaran menciptakan suasana yang menyenangkan, inklusif, kolaboratif, kreatif, dan efektif?","bobot":0},{"id":"q3","text":"Apakah pembelajaran memberikan kesempatan yang sama tanpa diskriminasi dan bersifat fleksibel?","bobot":0},{"id":"q4","text":"Apakah penilaian proses pembelajaran dilakukan untuk memperbaiki kualitas pembelajaran?","bobot":0},{"id":"q5","text":"Apakah standar proses dievaluasi secara periodik dan terus dilakukan perbaikan? (Konsistensi 3 tahun)","bobot":0},{"id":"q6","text":"Apakah pembelajaran dapat dilakukan secara tatap muka, daring, atau kombinasi keduanya?","bobot":0},{"id":"q7","text":"Apakah mahasiswa diberi keleluasaan mengikuti pendidikan dari berbagai tahapan kurikulum sesuai dengan kurikulum prodi?","bobot":0},{"id":"q8","text":"Apakah mahasiswa dapat menyelesaikan pendidikan melalui Rekognisi Pembelajaran Lampau (RPL)?","bobot":0},{"id":"q9","text":"Apakah pembelajaran bersifat inklusif terhadap peserta dengan berbagai latar belakang, usia, lokasi, sosial, budaya, dan ekonomi?","bobot":0},{"id":"q10","text":"Apakah persentase mahasiswa aktif yang memperoleh minimal 10 sks di luar Program Studi pada TS > 10%? (MBKM: pertukaran pelajar, magang, wirausaha, PkM, dll) (LKPS Tabel 2-I.6.1)","bobot":0}]');
INSERT INTO `Instrument` (`id`, `category`, `name`, `kriteria`, `indikator`, `jenjang_peruntukan`, `questions`) VALUES ('RP-10-S2', 'Relevansi Pendidikan', 'Standar & Fleksibilitas Proses Pembelajaran', '-', '-', 'S2', '[{"id":"q1","text":"Apakah standar perencanaan proses pembelajaran mencakup: perumusan CPL, strategi/metode pembelajaran, dan cara penilaian?","bobot":0},{"id":"q2","text":"Apakah pelaksanaan pembelajaran menciptakan suasana yang menyenangkan, inklusif, kolaboratif, kreatif, dan efektif?","bobot":0},{"id":"q3","text":"Apakah pembelajaran memberikan kesempatan yang sama tanpa diskriminasi dan bersifat fleksibel?","bobot":0},{"id":"q4","text":"Apakah penilaian proses pembelajaran dilakukan untuk memperbaiki kualitas pembelajaran?","bobot":0},{"id":"q5","text":"Apakah standar proses dievaluasi secara periodik dan terus dilakukan perbaikan? (Konsistensi 3 tahun)","bobot":0},{"id":"q6","text":"Apakah pendekatan research-based learning diterapkan dalam program magister?","bobot":0},{"id":"q7","text":"Apakah interaksi dosen-mahasiswa dalam seminar, diskusi, dan bimbingan tesis terdokumentasi?","bobot":0}]');
INSERT INTO `Instrument` (`id`, `category`, `name`, `kriteria`, `indikator`, `jenjang_peruntukan`, `questions`) VALUES ('RP-10-S3', 'Relevansi Pendidikan', 'Standar & Fleksibilitas Proses Pembelajaran', '-', '-', 'S3', '[{"id":"q1","text":"Apakah standar perencanaan proses pembelajaran mencakup: perumusan CPL, strategi/metode pembelajaran, dan cara penilaian?","bobot":0},{"id":"q2","text":"Apakah pelaksanaan pembelajaran menciptakan suasana yang menyenangkan, inklusif, kolaboratif, kreatif, dan efektif?","bobot":0},{"id":"q3","text":"Apakah pembelajaran memberikan kesempatan yang sama tanpa diskriminasi dan bersifat fleksibel?","bobot":0},{"id":"q4","text":"Apakah penilaian proses pembelajaran dilakukan untuk memperbaiki kualitas pembelajaran?","bobot":0},{"id":"q5","text":"Apakah standar proses dievaluasi secara periodik dan terus dilakukan perbaikan? (Konsistensi 3 tahun)","bobot":0},{"id":"q6","text":"Apakah pembelajaran berbasis riset (research-driven learning) diterapkan dalam program doktor?","bobot":0},{"id":"q7","text":"Apakah interaksi dosen-mahasiswa dalam seminar, diskusi, dan bimbingan disertasi terdokumentasi?","bobot":0}]');
INSERT INTO `Instrument` (`id`, `category`, `name`, `kriteria`, `indikator`, `jenjang_peruntukan`, `questions`) VALUES ('RP-11', 'Relevansi Pendidikan', 'Standar Penilaian Hasil Belajar', '-', '-', 'Semua', '[{"id":"q1","text":"Apakah standar penilaian hasil belajar mencakup prinsip: valid, reliabel, transparan, akuntabel, berkeadilan, objektif, dan edukatif?","bobot":0},{"id":"q2","text":"Apakah standar penilaian diimplementasikan secara konsisten dalam 3 tahun terakhir?","bobot":0},{"id":"q3","text":"Apakah rubrik/portofolio penilaian tersedia untuk minimal 70% matakuliah?","bobot":0},{"id":"q4","text":"Apakah penilaian dilakukan secara terintegrasi dan ada upaya perbaikan berkelanjutan?","bobot":0}]');
INSERT INTO `Instrument` (`id`, `category`, `name`, `kriteria`, `indikator`, `jenjang_peruntukan`, `questions`) VALUES ('RP-12', 'Relevansi Pendidikan', 'Efektivitas Kinerja & Prestasi Mahasiswa', '-', '-', 'S1', '[{"id":"q1","text":"Apakah rerata persentase penurunan lulusan (Re-PL) dalam 3 tahun terakhir ≤ 15%? (LKPS Tabel 2-I.7 Profil Jumlah Lulusan)","bobot":0},{"id":"q2","text":"Apakah Kelulusan 1× masa tempuh kurikulum Sarjana (PK1MTK) ≥ 45%? [Mahasiswa masuk TS-3, lulus s.d. TS; masa studi 3,5 ≤ MS ≤ 6 tahun] (LKPS Tabel 2-I.8d)","bobot":0},{"id":"q3","text":"Apakah Kelulusan 2× masa tempuh kurikulum Sarjana (PK2MTK) ≥ 75%? [Mahasiswa masuk TS-6, lulus s.d. TS; masa studi 6 ≤ MS ≤ 8 tahun] (LKPS Tabel 2-I.8d)","bobot":0},{"id":"q4","text":"Apakah persentase keterlibatan mahasiswa aktif dalam meraih prestasi (RPMP) ≥ 1%? [Prestasi tingkat wilayah/nasional/internasional, peringkat 1-3] (LKPS Tabel 2-I.12)","bobot":0},{"id":"q5","text":"Apakah rumusan CPL sesuai dengan profil lulusan yang kompeten dalam ranah keilmuan prodi?","bobot":0},{"id":"q6","text":"Apakah CPL selaras dengan KKNI level 6 and kebutuhan kompetensi DUDIK?","bobot":0},{"id":"q7","text":"Apakah pengukuran CPL dilakukan dengan metode yang tepat mencakup ranah sikap, pengetahuan, kecakapan umum/khusus, and kemampuan kerja?","bobot":0},{"id":"q8","text":"Apakah hasil pengukuran CPL ditindaklanjuti untuk perbaikan standar masukan and proses?","bobot":0},{"id":"q9","text":"Apakah capaian CPL dalam 3 tahun berturut-turut menunjukkan kategori ''sangat kompeten''? (Syarat Perlu Unggul)","bobot":0}]');
INSERT INTO `Instrument` (`id`, `category`, `name`, `kriteria`, `indikator`, `jenjang_peruntukan`, `questions`) VALUES ('RP-13', 'Relevansi Pendidikan', 'Pendidikan Anti Korupsi', '-', '-', 'Semua', '[{"id":"q1","text":"Apakah terdapat internalisasi pendidikan anti korupsi dalam pembelajaran program studi?","bobot":0},{"id":"q2","text":"Apakah PAK disisipkan/diintegrasikan sekurang-kurangnya pada 10 sks (MKWU atau matakuliah relevan)?","bobot":0},{"id":"q3","text":"Apakah terdapat dokumentasi pelaksanaan PAK (modul, RPS, laporan)?","bobot":0}]');
INSERT INTO `Instrument` (`id`, `category`, `name`, `kriteria`, `indikator`, `jenjang_peruntukan`, `questions`) VALUES ('RP-14', 'Relevansi Pendidikan', 'Pengakuan & Kepuasan Pengguna Lulusan', '-', '-', 'Semua', '[{"id":"q1","text":"Apakah lulusan mendapatkan pengakuan/sertifikasi profesional dalam 3 tahun terakhir? (Min. 3 pengakuan nasional atau 1 tingkat internasional – sesuai fokus diferensiasi misi)","bobot":0},{"id":"q2","text":"Apakah pengakuan/sertifikasi tersebut dari instansi atau lembaga yang berkompeten di tingkat lokal, nasional, atau internasional?","bobot":0},{"id":"q3","text":"Apakah survey kepuasan pengguna lulusan dilaksanakan dengan instrumen yang sahih dan andal?","bobot":0},{"id":"q4","text":"Apakah data survey kepuasan dilaksanakan secara berkala dan representatif (lulusan TS-1 s.d. TS-3)?","bobot":0},{"id":"q5","text":"Apakah hasil survey kepuasan dianalisis dan digunakan untuk perbaikan kurikulum berkelanjutan?","bobot":0},{"id":"q6","text":"Apakah tingkat kepuasan pengguna lulusan pada aspek: etika, kompetensi, bahasa asing, TI, komunikasi, kerjasama, pengembangan diri ≥ Baik?","bobot":0}]');
INSERT INTO `Instrument` (`id`, `category`, `name`, `kriteria`, `indikator`, `jenjang_peruntukan`, `questions`) VALUES ('RP-15', 'Relevansi Pendidikan', 'Daya Tarik Prodi & Keterserapan Lulusan', '-', '-', 'S1', '[{"id":"q1","text":"Apakah rerata persentase penurunan mahasiswa baru Sarjana (RPPM) dalam 5 tahun terakhir ≤ 15%? (LKPS Tabel 2-I.9 Trend Jumlah Mahasiswa Baru)","bobot":0},{"id":"q2","text":"Apakah persentase lulusan yang terserap lapangan kerja / melanjutkan pendidikan / berwirausaha dalam ≤ 1 tahun setelah lulus (PLTLK) ≥ 40%? [Mengacu pada lulusan tahun TS-2] (LKPS Tabel 2-I.11 Waktu Tunggu Lulusan)","bobot":0},{"id":"q3","text":"Apakah terdapat bukti tracer study yang valid dan representatif untuk mengukur keterserapan lulusan?","bobot":0},{"id":"q4","text":"Apakah hasil tracer study digunakan untuk perbaikan kurikulum dan layanan kemahasiswaan?","bobot":0},{"id":"q5","text":"Apakah tren penerimaan mahasiswa baru dalam 5 tahun menunjukkan stabilitas atau pertumbuhan?","bobot":0}]');
INSERT INTO `Instrument` (`id`, `category`, `name`, `kriteria`, `indikator`, `jenjang_peruntukan`, `questions`) VALUES ('RP-015', 'Relevansi Pendidikan', 'Daya Tarik Prodi & Keterserapan Lulusan', '-', '-', 'S2', '[{"id":"q1","text":"Apakah jumlah mahasiswa aktif (NMA) dalam 3 tahun terakhir ≥ 15 orang per tahun? (LKPS Tabel 2-I.9)","bobot":0},{"id":"q2","text":"Apakah Rerata Persentase Publikasi Ilmiah Internasional bereputasi, internasional, dan nasional DPR (PPID) ≥ 30%?","bobot":0},{"id":"q3","text":"Apakah Rerata Persentase Karya Ilmiah DPR yang digunakan masyarakat/industri (RPKID) ≥ 30%? (Syarat Perlu Unggul)","bobot":0},{"id":"q4","text":"Apakah tren penerimaan mahasiswa baru dalam 3 tahun menunjukkan stabilitas atau peningkatan?","bobot":0}]');
INSERT INTO `Instrument` (`id`, `category`, `name`, `kriteria`, `indikator`, `jenjang_peruntukan`, `questions`) VALUES ('RP-0015', 'Relevansi Pendidikan', 'Daya Tarik Prodi & Keterserapan Lulusan', '-', '-', 'S3', '[{"id":"q1","text":"Apakah jumlah mahasiswa aktif (NMA) dalam 3 tahun terakhir ≥ 15 orang per tahun? (LKPS Tabel 2-I.9)","bobot":0},{"id":"q2","text":"Apakah Rerata Persentase Publikasi Ilmiah Internasional bereputasi, internasional, dan nasional DPR (PPID) ≥ 60%?","bobot":0},{"id":"q3","text":"Apakah Rerata Persentase Karya Ilmiah DPR yang digunakan masyarakat/industri (RPKID) ≥ 40%? (Syarat Perlu Unggul)","bobot":0},{"id":"q4","text":"Apakah tren penerimaan mahasiswa baru dalam 3 tahun menunjukkan stabilitas atau peningkatan?","bobot":0}]');
INSERT INTO `Instrument` (`id`, `category`, `name`, `kriteria`, `indikator`, `jenjang_peruntukan`, `questions`) VALUES ('RR-16', 'Relevansi Penelitian', 'Penugasan & Standar Masukan Penelitian', '-', '-', 'Semua', '[{"id":"q1","text":"Apakah terdapat peta jalan (roadmap) penelitian yang memayungi tema penelitian dosen dan mahasiswa?","bobot":0},{"id":"q2","text":"Apakah roadmap penelitian mengacu pada visi keilmuan prodi and fokus diferensiasi misi PT serta target berdampak?","bobot":0},{"id":"q3","text":"Apakah dosen dan mahasiswa melaksanakan penelitian sesuai agenda yang merujuk pada roadmap?","bobot":0},{"id":"q4","text":"Apakah evaluasi kesesuaian penelitian dengan roadmap dilakukan dan hasilnya digunakan untuk perbaikan?","bobot":0},{"id":"q5","text":"Apakah UPPS menyediakan akses memadai terhadap sarana, prasarana, and pembiayaan penelitian?","bobot":0},{"id":"q6","text":"Apakah terdapat penugasan and peningkatan kompetensi dosen dalam penelitian secara terstruktur?","bobot":0},{"id":"q7","text":"Apakah terdapat sistem TIK untuk mendokumentasikan, mengevaluasi, melaporkan, and menyebarluaskan hasil penelitian?","bobot":0},{"id":"q8","text":"Apakah standar masukan penelitian mempertimbangkan diferensiasi misi PT and target berdampak?","bobot":0},{"id":"q9","text":"Apakah sistem TIK penelitian mendukung dokumentasi and evaluasi penelitian?","bobot":0},{"id":"q10","text":"Apakah sistem TIK mendukung penyebarluasan hasil penelitian?","bobot":0}]');
INSERT INTO `Instrument` (`id`, `category`, `name`, `kriteria`, `indikator`, `jenjang_peruntukan`, `questions`) VALUES ('RR-17', 'Relevansi Penelitian', 'Pelaksanaan Penelitian & Integrasi Kurikulum', '-', '-', 'Semua', '[{"id":"q1","text":"Apakah terdapat bukti sahih pelaksanaan penelitian yang melibatkan mahasiswa dalam 3 tahun terakhir?","bobot":0},{"id":"q2","text":"Apakah mahasiswa yang terlibat dalam penelitian dosen dapat menerima satuan kredit semester (SKS)?","bobot":0},{"id":"q3","text":"Apakah penelitian yang melibatkan mahasiswa memenuhi kaidah and metode ilmiah sesuai otonomi keilmuan?","bobot":0},{"id":"q4","text":"Apakah ada perbaikan kualitas penelitian secara berkelanjutan?","bobot":0},{"id":"q5","text":"Apakah hasil penelitian diintegrasikan ke dalam kurikulum sebagai bahan kajian pengayaan berbasis riset?","bobot":0},{"id":"q6","text":"Apakah integrasi dilakukan secara konsisten and dievaluasi untuk pengembangan program studi?","bobot":0}]');
INSERT INTO `Instrument` (`id`, `category`, `name`, `kriteria`, `indikator`, `jenjang_peruntukan`, `questions`) VALUES ('RR-18', 'Relevansi Penelitian', 'Luaran & Publikasi Penelitian DPR', '-', '-', 'Semua', '[{"id":"q1","text":"Apakah luaran penelitian mengadopsi lisensi terbuka and dapat diakses masyarakat?","bobot":0},{"id":"q2","text":"Apakah terdapat analisis keberlanjutan penelitian sesuai roadmap and realisasi dana penelitian?","bobot":0},{"id":"q3","text":"Apakah terdapat analisis ketercapaian luaran penelitian: a) publikasi, b) HKI, c) produk/jasa, d) Buku/Book Chapter?","bobot":0},{"id":"q4","text":"Apakah ketercapaian luaran sesuai dengan indikator kinerja and target yang ditetapkan PT?","bobot":0},{"id":"q5","text":"Apakah RLP (Rerata Luaran Publikasi) mencapai 100% dari seluruh DPR? RLP = (NA2+NA3+NA4+NB2+NB3) / NDPR × 100% [NA2=jurnal nasional SINTA 1-2; NA3=intl; NA4=intl bereputasi; NB2=seminar nasional; NB3=seminar intl bereputasi]","bobot":0},{"id":"q6","text":"Apakah terdapat publikasi di jurnal internasional bereputasi (Scopus/WoS) oleh DPR?","bobot":0},{"id":"q7","text":"Apakah terdapat publikasi di jurnal nasional terakreditasi SINTA 1/2 oleh DPR?","bobot":0},{"id":"q8","text":"Apakah terdapat presentasi di seminar internasional bereputasi oleh DPR?","bobot":0}]');
INSERT INTO `Instrument` (`id`, `category`, `name`, `kriteria`, `indikator`, `jenjang_peruntukan`, `questions`) VALUES ('RR-19', 'Relevansi Penelitian', 'Rekognisi & Sitasi Karya Ilmiah', '-', '-', 'S1', '[{"id":"q1","text":"Apakah terdapat luaran penelitian berupa HKI: Paten/Paten Sederhana dari DPR bersama mahasiswa?","bobot":0},{"id":"q2","text":"Apakah terdapat luaran HKI lainnya: Hak Cipta, Desain Produk Industri, Perlindungan Varietas Tanaman, dll.?","bobot":0},{"id":"q3","text":"Apakah luaran penelitian menunjukkan adanya kolaborasi, sitasi, and rekognisi bidang keilmuan yang termanfaatkan DUDIK/masyarakat?","bobot":0},{"id":"q4","text":"Apakah DPR mendapat rekognisi: visiting professor, keynote/invited speaker, staf ahli nasional/internasional?","bobot":0},{"id":"q5","text":"Apakah DPR menjadi editor/mitra bestari jurnal nasional terakreditasi atau internasional bereputasi?","bobot":0},{"id":"q6","text":"Apakah DPR mendapat penghargaan atas prestasi/kinerja tingkat nasional/internasional?","bobot":0},{"id":"q7","text":"Apakah Rasio Rekognisi Dosen (RRD) mencapai 100% dari seluruh DPR? RRD = (NRD / NDPR) × 100% (LKPS Tabel 2-II.7)","bobot":0}]');
INSERT INTO `Instrument` (`id`, `category`, `name`, `kriteria`, `indikator`, `jenjang_peruntukan`, `questions`) VALUES ('RR-019', 'Relevansi Penelitian', 'Rekognisi & Sitasi Karya Ilmiah', '-', '-', 'S2', '[{"id":"q1","text":"Apakah terdapat bukti kolaborasi, sitasi, and rekognisi bidang keilmuan DPR dalam 3 tahun terakhir?","bobot":0},{"id":"q2","text":"Apakah luaran penelitian termanfaatkan oleh DUDIK and masyarakat?","bobot":0},{"id":"q3","text":"Apakah Rasio Sitasi (RS) ≥ 100% dari seluruh DPR? RS = (NAS / NDPR) × 100% (LKPS Tabel 2-II.9)","bobot":0},{"id":"q4","text":"Apakah DPR mendapat rekognisi: visiting professor, keynote/invited speaker, staf ahli nasional/internasional?","bobot":0},{"id":"q5","text":"Apakah DPR menjadi editor/mitra bestari jurnal nasional terakreditasi atau internasional bereputasi?","bobot":0},{"id":"q6","text":"Apakah Rasio Rekognisi Dosen (RRD) mencapai 100% dari seluruh DPR? RRD = (NRD / NDPR) × 100% (LKPS Tabel 2-II.7)","bobot":0}]');
INSERT INTO `Instrument` (`id`, `category`, `name`, `kriteria`, `indikator`, `jenjang_peruntukan`, `questions`) VALUES ('RR-0019', 'Relevansi Penelitian', 'Rekognisi & Sitasi Karya Ilmiah', '-', '-', 'S3', '[{"id":"q1","text":"Apakah terdapat bukti kolaborasi, sitasi, and rekognisi bidang keilmuan DPR dalam 3 tahun terakhir?","bobot":0},{"id":"q2","text":"Apakah luaran penelitian termanfaatkan oleh DUDIK and masyarakat?","bobot":0},{"id":"q3","text":"Apakah Rasio Sitasi (RS) ≥ 100% dari seluruh DPR? RS = (NAS / NDPR) × 100% (LKPS Tabel 2-II.9)","bobot":0},{"id":"q4","text":"Apakah DPR mendapat rekognisi berupa: visiting professor, keynote speaker, staf ahli nasional/internasional?","bobot":0},{"id":"q5","text":"Apakah DPR menjadi editor/mitra bestari jurnal nasional terakreditasi atau jurnal internasional bereputasi?","bobot":0},{"id":"q6","text":"Apakah Rasio Rekognisi Dosen (RRD) mencapai 100% dari seluruh DPR? (LKPS Tabel 2-II.7)","bobot":0}]');
INSERT INTO `Instrument` (`id`, `category`, `name`, `kriteria`, `indikator`, `jenjang_peruntukan`, `questions`) VALUES ('RPM-20', 'Relevansi Pengabdian Kepada Masyarakat', 'Penugasan & Standar Masukan PkM', '-', '-', 'S1', '[{"id":"q1","text":"Apakah terdapat roadmap PkM yang memayungi tema PkM dosen and mahasiswa serta hilirisasi keilmuan prodi and target berdampak?","bobot":0},{"id":"q2","text":"Apakah roadmap PkM mengacu pada visi keilmuan prodi and diferensiasi misi PT?","bobot":0},{"id":"q3","text":"Apakah dosen and mahasiswa melaksanakan PkM sesuai peta jalan?","bobot":0},{"id":"q4","text":"Apakah evaluasi kesesuaian PkM dengan roadmap dilakukan and digunakan untuk perbaikan and target berdampak?","bobot":0},{"id":"q5","text":"Apakah UPPS menyediakan akses memadai terhadap sarana, prasarana, and pembiayaan PkM?","bobot":0},{"id":"q6","text":"Apakah penugasan and peningkatan kompetensi dosen dalam PkM terstruktur?","bobot":0},{"id":"q7","text":"Apakah terdapat sistem TIK untuk mendokumentasikan, mengevaluasi, and menyebarluaskan hasil PkM?","bobot":0},{"id":"q8","text":"Apakah standar masukan PkM mempertimbangkan diferensiasi misi PT and target berdampak?","bobot":0}]');
INSERT INTO `Instrument` (`id`, `category`, `name`, `kriteria`, `indikator`, `jenjang_peruntukan`, `questions`) VALUES ('RPM-020', 'Relevansi Pengabdian Kepada Masyarakat', 'Penugasan & Standar Masukan PkM', '-', '-', 'S2', '[{"id":"q1","text":"Apakah terdapat roadmap PkM yang memayungi tema PkM dosen and mahasiswa serta hilirisasi keilmuan prodi?","bobot":0},{"id":"q2","text":"Apakah roadmap PkM mengacu pada visi keilmuan prodi and diferensiasi misi PT?","bobot":0},{"id":"q3","text":"Apakah dosen and mahasiswa melaksanakan PkM sesuai peta jalan?","bobot":0},{"id":"q4","text":"Apakah evaluasi kesesuaian PkM dengan roadmap dilakukan and digunakan untuk perbaikan?","bobot":0},{"id":"q5","text":"Apakah roadmap PkM mendukung pengembangan kualitas kepakaran dosen?","bobot":0},{"id":"q6","text":"Apakah UPPS menyediakan akses memadai terhadap sarana, prasarana, and pembiayaan PkM?","bobot":0},{"id":"q7","text":"Apakah penugasan and peningkatan kompetensi dosen dalam PkM terstruktur?","bobot":0},{"id":"q8","text":"Apakah terdapat sistem TIK untuk mendokumentasikan, mengevaluasi, and menyebarluaskan hasil PkM?","bobot":0},{"id":"q9","text":"Apakah standar masukan PkM mempertimbangkan diferensiasi misi PT?","bobot":0}]');
INSERT INTO `Instrument` (`id`, `category`, `name`, `kriteria`, `indikator`, `jenjang_peruntukan`, `questions`) VALUES ('RPM-0020', 'Relevansi Pengabdian Kepada Masyarakat', 'Penugasan & Standar Masukan PkM', '-', '-', 'S3', '[{"id":"q1","text":"Apakah terdapat roadmap PkM yang memayungi tema PkM dosen and mahasiswa serta hilirisasi keilmuan prodi?","bobot":0},{"id":"q2","text":"Apakah roadmap PkM mengacu pada visi keilmuan prodi and diferensiasi misi PT?","bobot":0},{"id":"q3","text":"Apakah dosen and mahasiswa melaksanakan PkM sesuai peta jalan?","bobot":0},{"id":"q4","text":"Apakah evaluasi kesesuaian PkM dengan roadmap dilakukan and digunakan untuk perbaikan?","bobot":0},{"id":"q5","text":"Apakah roadmap PkM mendukung pengembangan kualitas kepakaran dosen?","bobot":0},{"id":"q6","text":"Apakah UPPS menyediakan akses memadai terhadap sarana, prasarana, and pembiayaan PkM?","bobot":0},{"id":"q7","text":"Apakah penugasan and peningkatan kompetensi dosen dalam PkM terstruktur?","bobot":0},{"id":"q8","text":"Apakah terdapat sistem TIK untuk mendokumentasikan, mengevaluasi, and menyebarluaskan hasil PkM?","bobot":0},{"id":"q9","text":"Apakah standar masukan PkM mempertimbangkan diferensiasi misi PT?","bobot":0}]');
INSERT INTO `Instrument` (`id`, `category`, `name`, `kriteria`, `indikator`, `jenjang_peruntukan`, `questions`) VALUES ('RPM-21', 'Relevansi Pengabdian Kepada Masyarakat', 'Pelaksanaan PkM & Integrasi ke Kurikulum', '-', '-', 'Semua', '[{"id":"q1","text":"Apakah PkM dosen bersama mahasiswa memenuhi keterlaksanaan kode etik PkM?","bobot":0},{"id":"q2","text":"Apakah pengelolaan dan kepemilikan HKI hasil PkM sesuai ketentuan perundangan?","bobot":0},{"id":"q3","text":"Apakah terdapat ketentuan dalam pelaksanaan kerja sama PkM?","bobot":0},{"id":"q4","text":"Apakah terdapat persyaratan dan ketentuan diseminasi hasil PkM?","bobot":0},{"id":"q5","text":"Apakah perbaikan kualitas PkM dilakukan secara berkelanjutan?","bobot":0},{"id":"q6","text":"Apakah hasil PkM diintegrasikan ke dalam kurikulum untuk pengembangan program studi?","bobot":0},{"id":"q7","text":"Apakah integrasi hasil PkM ke kurikulum berjalan konsisten dan dievaluasi?","bobot":0}]');
INSERT INTO `Instrument` (`id`, `category`, `name`, `kriteria`, `indikator`, `jenjang_peruntukan`, `questions`) VALUES ('RPM-22', 'Relevansi Pengabdian Kepada Masyarakat', 'Luaran & Rekognisi PkM', '-', '-', 'Semua', '[{"id":"q1","text":"Apakah luaran PkM mengadopsi lisensi terbuka dan dapat diakses masyarakat?","bobot":0},{"id":"q2","text":"Apakah terdapat pengembangan kapasitas SDM dari hasil PkM?","bobot":0},{"id":"q3","text":"Apakah terdapat ragam layanan terlembaga dari hasil PkM?","bobot":0},{"id":"q4","text":"Apakah kepuasan mitra kerjasama PkM diukur dan didokumentasikan?","bobot":0},{"id":"q5","text":"Apakah realisasi sumber dana pengabdian terdokumentasi dan mencukupi?","bobot":0},{"id":"q6","text":"Apakah terdapat rekognisi atas luaran PkM sesuai bidang keilmuan prodi (karya DPR yang terekognisi/diterapkan masyarakat)?","bobot":0}]');
INSERT INTO `Instrument` (`id`, `category`, `name`, `kriteria`, `indikator`, `jenjang_peruntukan`, `questions`) VALUES ('RPM-23', 'Relevansi Pengabdian Kepada Masyarakat', 'Pengakuan Kepakaran & HKI Dosen', '-', '-', 'Semua', '[{"id":"q1","text":"Apakah DPR mendapat pengakuan kepakaran profesional dari masyarakat, pemerintah, atau industri?","bobot":0},{"id":"q2","text":"Apakah Rasio Rekognisi Dosen (RRD) ≥ 100% dari seluruh DPR?","bobot":0},{"id":"q3","text":"Apakah terdapat karya DPR atau bersama mahasiswa berupa Paten/Paten Sederhana?","bobot":0},{"id":"q4","text":"Apakah terdapat HKI lainnya: Hak Cipta, Desain Produk Industri, Perlindungan Varietas Tanaman, dll.?","bobot":0},{"id":"q5","text":"Apakah terdapat Teknologi Tepat Guna, Produk Terstandarisasi/Tersertifikasi, Karya Seni, Rekayasa Sosial?","bobot":0},{"id":"q6","text":"Apakah Rasio HKI (RHKI) ≥ 100% dari seluruh DPR? RHKI = (NA+NB+NC) / NDPR × 100%","bobot":0}]');
INSERT INTO `Instrument` (`id`, `category`, `name`, `kriteria`, `indikator`, `jenjang_peruntukan`, `questions`) VALUES ('AK-24', 'Akuntabilitas', 'Tata Pamong – SOTK & Renstra Pendidikan', '-', '-', 'Semua', '[{"id":"q1","text":"Apakah terdapat dokumen formal Struktur Organisasi dan Tata Kerja (SOTK) yang lengkap mencakup: penyusun kebijakan, pelaksana akademik, pengawas/penjaminan mutu, penunjang akademik, pelaksana administrasi?","bobot":0},{"id":"q2","text":"Apakah renstra pengembangan pendidikan UPPS tersedia dan mencakup Program Studi yang diakreditasi?","bobot":0},{"id":"q3","text":"Apakah SOTK dan renstra ditetapkan dengan ketetapan formal dan berjalan efektif?","bobot":0},{"id":"q4","text":"Apakah renstra mencakup peta pengembangan jangka panjang, menengah, dan pendek dengan indikator terukur?","bobot":0}]');
INSERT INTO `Instrument` (`id`, `category`, `name`, `kriteria`, `indikator`, `jenjang_peruntukan`, `questions`) VALUES ('AK-25', 'Akuntabilitas', 'Sistem Tata Pamong & Mitigasi Risiko', '-', '-', 'Semua', '[{"id":"q1","text":"Apakah pengawasan dan pengendalian kegiatan pendidikan dilakukan dalam bidang akademik dan nonakademik?","bobot":0},{"id":"q2","text":"Apakah terdapat pemantauan dan evaluasi pelaksanaan kegiatan pendidikan serta efektivitas kebijakan akademik?","bobot":0},{"id":"q3","text":"Apakah pemantauan potensi risiko (korupsi, pengaduan, penurunan data PD Dikti) dilakukan?","bobot":0},{"id":"q4","text":"Apakah terdapat penjaminan kepatuhan pada otoritas akademik dan etika akademik?","bobot":0},{"id":"q5","text":"Apakah terdapat sistem penerimaan, pendokumentasian, dan penyelesaian keluhan/pengaduan?","bobot":0},{"id":"q6","text":"Apakah terdapat pelaporan dan akuntabilitas terhadap penggunaan bantuan pendanaan dari mitra?","bobot":0},{"id":"q7","text":"Apakah UPPS memenuhi ketentuan peraturan ketenagakerjaan (UU No.13/2003) dan ASN (UU No.20/2023)?","bobot":0}]');
INSERT INTO `Instrument` (`id`, `category`, `name`, `kriteria`, `indikator`, `jenjang_peruntukan`, `questions`) VALUES ('AK-26', 'Akuntabilitas', 'Sistem TIK Pengelolaan Data & Informasi', '-', '-', 'Semua', '[{"id":"q1","text":"Apakah terdapat kebijakan formal terkait pengembangan sarana TIK untuk manajemen dan pengelolaan data?","bobot":0},{"id":"q2","text":"Apakah sistem TIK memastikan keamanan, kebenaran, akurasi, kelengkapan, dan kemutakhiran data akademik?","bobot":0},{"id":"q3","text":"Apakah sistem TIK mendukung perencanaan, pelaksanaan, pengawasan, dan pengambilan keputusan?","bobot":0},{"id":"q4","text":"Apakah data profil dan kinerja prodi dilaporkan ke PD Dikti sesuai ketentuan perundangan?","bobot":0},{"id":"q5","text":"Apakah data dan informasi prodi dapat diakses publik?","bobot":0},{"id":"q6","text":"Apakah terdapat rencana pengembangan TIK untuk mendukung kegiatan pendidikan?","bobot":0}]');
INSERT INTO `Instrument` (`id`, `category`, `name`, `kriteria`, `indikator`, `jenjang_peruntukan`, `questions`) VALUES ('AK-27', 'Akuntabilitas', 'Efektivitas Kepemimpinan UPPS & Prodi', '-', '-', 'Semua', '[{"id":"q1","text":"Apakah terdapat bukti sahih kepemimpinan operasional yang menggerakkan seluruh sumber daya internal secara optimal?","bobot":0},{"id":"q2","text":"Apakah terdapat bukti kepemimpinan organisasional yang menggerakkan dan mengharmonisasikan suasana kerja kondusif?","bobot":0},{"id":"q3","text":"Apakah terdapat bukti kepemimpinan publik berupa kerjasama yang menjadikan prodi sebagai rujukan masyarakat?","bobot":0},{"id":"q4","text":"Apakah efektivitas kepemimpinan mencakup ketiga aspek tersebut secara konsisten?","bobot":0}]');
INSERT INTO `Instrument` (`id`, `category`, `name`, `kriteria`, `indikator`, `jenjang_peruntukan`, `questions`) VALUES ('AK-28', 'Akuntabilitas', 'Good University Governance (GUG)', '-', '-', 'Semua', '[{"id":"q1","text":"Apakah terdapat dokumen formal GUG mencakup 6 aspek: kredibilitas, transparansi, akuntabilitas, tanggung jawab, berkeadilan, dan manajemen risiko?","bobot":0},{"id":"q2","text":"Apakah implementasi GUG berjalan konsisten di lingkungan UPPS?","bobot":0},{"id":"q3","text":"Apakah UPPS mengumumkan ringkasan laporan tahunan kepada masyarakat?","bobot":0},{"id":"q4","text":"Apakah terdapat lembaga/unit penegakan kode etik yang berfungsi efektif dengan pedoman formal?","bobot":0},{"id":"q5","text":"Apakah terdapat kebijakan dan bukti implementasi kampus bebas kekerasan seksual, perundungan, dan diskriminasi?","bobot":0},{"id":"q6","text":"Apakah ada penanganan dan penindakan kasus kekerasan seksual/perundungan/intoleransi di UPPS?","bobot":0}]');
INSERT INTO `Instrument` (`id`, `category`, `name`, `kriteria`, `indikator`, `jenjang_peruntukan`, `questions`) VALUES ('AK-29', 'Akuntabilitas', 'Pengelolaan Fungsional & Operasional UPPS', '-', '-', 'Semua', '[{"id":"q1","text":"Apakah terdapat bukti formal keberfungsian perencanaan (planning) di UPPS?","bobot":0},{"id":"q2","text":"Apakah terdapat bukti formal keberfungsian pengorganisasian (organizing)?","bobot":0},{"id":"q3","text":"Apakah terdapat bukti formal keberfungsian penempatan personil (staffing)?","bobot":0},{"id":"q4","text":"Apakah terdapat bukti formal keberfungsian pengarahan (leading)?","bobot":0},{"id":"q5","text":"Apakah terdapat bukti formal keberfungsian pengawasan (controlling)?","bobot":0},{"id":"q6","text":"Apakah kelima aspek pengelolaan fungsional dan operasional berjalan konsisten?","bobot":0}]');
INSERT INTO `Instrument` (`id`, `category`, `name`, `kriteria`, `indikator`, `jenjang_peruntukan`, `questions`) VALUES ('AK-30', 'Akuntabilitas', 'Suasana Akademik Program Studi', '-', '-', 'S1', '[{"id":"q1","text":"Apakah terdapat dokumen formal kebijakan suasana akademik: otonomi keilmuan, kebebasan akademik, dan kebebasan mimbar akademik?","bobot":0},{"id":"q2","text":"Apakah kegiatan tridharma menjunjung tinggi integritas dan etika akademik?","bobot":0},{"id":"q3","text":"Apakah suasana akademik yang kondusif terwujud secara konsisten setiap bulan?","bobot":0},{"id":"q4","text":"Apakah terdapat kegiatan seminar, diskusi ilmiah, kuliah tamu, dan kegiatan akademik kemahasiswaan secara rutin?","bobot":0}]');
INSERT INTO `Instrument` (`id`, `category`, `name`, `kriteria`, `indikator`, `jenjang_peruntukan`, `questions`) VALUES ('AK-030', 'Akuntabilitas', 'Suasana Akademik Program Studi', '-', '-', 'S2', '[{"id":"q1","text":"Apakah terdapat dokumen formal kebijakan suasana akademik: otonomi keilmuan, kebebasan akademik, dan kebebasan mimbar akademik?","bobot":0},{"id":"q2","text":"Apakah kegiatan tridharma menjunjung tinggi integritas dan etika akademik?","bobot":0},{"id":"q3","text":"Apakah suasana akademik yang kondusif terwujud secara konsisten setiap bulan?","bobot":0},{"id":"q4","text":"Apakah terdapat kegiatan seminar, diskusi ilmiah, dan kolokium secara rutin dalam program magister?","bobot":0}]');
INSERT INTO `Instrument` (`id`, `category`, `name`, `kriteria`, `indikator`, `jenjang_peruntukan`, `questions`) VALUES ('AK-0030', 'Akuntabilitas', 'Suasana Akademik Program Studi', '-', '-', 'S3', '[{"id":"q1","text":"Apakah terdapat dokumen formal kebijakan suasana akademik yang mencakup: otonomi keilmuan, kebebasan akademik, dan kebebasan mimbar akademik?","bobot":0},{"id":"q2","text":"Apakah kegiatan tridharma di PT menjunjung tinggi integritas dan etika akademik?","bobot":0},{"id":"q3","text":"Apakah suasana akademik yang kondusif terwujud secara konsisten setiap bulan?","bobot":0},{"id":"q4","text":"Apakah terdapat kegiatan seminar, diskusi ilmiah, dan koloqium secara rutin dalam program doktor?","bobot":0}]');
INSERT INTO `Instrument` (`id`, `category`, `name`, `kriteria`, `indikator`, `jenjang_peruntukan`, `questions`) VALUES ('AK-31', 'Akuntabilitas', 'Kebijakan Penerimaan Mahasiswa Baru', '-', '-', 'Semua', '[{"id":"q1","text":"Apakah terdapat kebijakan penerimaan mahasiswa baru yang afirmatif, inklusif, dan adil (tidak diskriminatif atas suku, ras, agama, disabilitas)?","bobot":0},{"id":"q2","text":"Apakah terdapat upaya perluasan akses melalui: a) Pembelajaran Jarak Jauh (PJJ)?","bobot":0},{"id":"q3","text":"Apakah terdapat sharing sumber daya pembelajaran antar institusi?","bobot":0},{"id":"q4","text":"Apakah terdapat skema beasiswa: afirmasi, 3T, mahasiswa berprestasi tidak mampu, minat/bakat?","bobot":0},{"id":"q5","text":"Apakah terdapat kebijakan rekrutmen melalui Rekognisi Pembelajaran Lampau (RPL)?","bobot":0}]');
INSERT INTO `Instrument` (`id`, `category`, `name`, `kriteria`, `indikator`, `jenjang_peruntukan`, `questions`) VALUES ('AK-32', 'Akuntabilitas', 'Sistem Layanan Mahasiswa', '-', '-', 'S1', '[{"id":"q1","text":"Apakah terdapat program penyiapan mahasiswa baru mencakup 4 aspek: penjelasan umum PT, integritas akademik, bebas kekerasan, dan adaptasi kampus?","bobot":0},{"id":"q2","text":"Apakah terdapat layanan administrasi akademik yang memadai?","bobot":0},{"id":"q3","text":"Apakah terdapat layanan bimbingan konseling?","bobot":0},{"id":"q4","text":"Apakah terdapat layanan kesehatan?","bobot":0},{"id":"q5","text":"Apakah terdapat layanan keperluan dasar mahasiswa berkebutuhan khusus?","bobot":0},{"id":"q6","text":"Apakah terdapat layanan pemenuhan beban belajar di luar program studi? (MBKM: magang, pertukaran pelajar, wirausaha, dll.)","bobot":0},{"id":"q7","text":"Apakah dilakukan survey kepuasan atas layanan mahasiswa?","bobot":0}]');
INSERT INTO `Instrument` (`id`, `category`, `name`, `kriteria`, `indikator`, `jenjang_peruntukan`, `questions`) VALUES ('AK-032', 'Akuntabilitas', 'Sistem Layanan Mahasiswa', '-', '-', 'S2', '[{"id":"q1","text":"Apakah terdapat program penyiapan mahasiswa baru mencakup 4 aspek: penjelasan umum PT, integritas akademik, bebas kekerasan, dan adaptasi kampus?","bobot":0},{"id":"q2","text":"Apakah terdapat layanan administrasi akademik yang memadai?","bobot":0},{"id":"q3","text":"Apakah terdapat layanan bimbingan konseling?","bobot":0},{"id":"q4","text":"Apakah terdapat layanan kesehatan?","bobot":0},{"id":"q5","text":"Apakah terdapat layanan keperluan dasar mahasiswa berkebutuhan khusus?","bobot":0},{"id":"q6","text":"Apakah dilakukan survey kepuasan atas layanan mahasiswa?","bobot":0}]');
INSERT INTO `Instrument` (`id`, `category`, `name`, `kriteria`, `indikator`, `jenjang_peruntukan`, `questions`) VALUES ('AK-0032', 'Akuntabilitas', 'Sistem Layanan Mahasiswa', '-', '-', 'S3', '[{"id":"q1","text":"Apakah terdapat program penyiapan mahasiswa baru mencakup 4 aspek: penjelasan umum PT, integritas akademik, bebas kekerasan, dan adaptasi kehidupan kampus?","bobot":0},{"id":"q2","text":"Apakah terdapat layanan administrasi akademik yang memadai?","bobot":0},{"id":"q3","text":"Apakah terdapat layanan bimbingan konseling?","bobot":0},{"id":"q4","text":"Apakah terdapat layanan kesehatan?","bobot":0},{"id":"q5","text":"Apakah terdapat layanan keperluan dasar mahasiswa berkebutuhan khusus?","bobot":0},{"id":"q6","text":"Apakah dilakukan survey kepuasan atas layanan mahasiswa?","bobot":0}]');
INSERT INTO `Instrument` (`id`, `category`, `name`, `kriteria`, `indikator`, `jenjang_peruntukan`, `questions`) VALUES ('AK-33', 'Akuntabilitas', 'Implementasi Layanan Berintegritas', '-', '-', 'Semua', '[{"id":"q1","text":"Apakah terdapat dokumen dan bukti sahih implementasi layanan yang berintegritas (bersih dan melayani)?","bobot":0},{"id":"q2","text":"Apakah layanan berintegritas dievaluasi secara periodik (triwulan)?","bobot":0},{"id":"q3","text":"Apakah terdapat prosedur formal layanan yang bersih dan profesional?","bobot":0}]');
INSERT INTO `Instrument` (`id`, `category`, `name`, `kriteria`, `indikator`, `jenjang_peruntukan`, `questions`) VALUES ('AK-34', 'Akuntabilitas', 'Kepuasan Pemangku Kepentingan (Tata Pamong)', '-', '-', 'Semua', '[{"id":"q1","text":"Apakah survey kepuasan menggunakan instrumen yang sahih, andal, dan mudah digunakan?","bobot":0},{"id":"q2","text":"Apakah survey kepuasan dilaksanakan secara berkala and datanya terekam komprehensif?","bobot":0},{"id":"q3","text":"Apakah hasil survey dianalisis dengan metode yang tepat untuk pengambilan keputusan?","bobot":0},{"id":"q4","text":"Apakah umpan balik kepuasan ditindaklanjuti untuk perbaikan mutu secara berkala?","bobot":0},{"id":"q5","text":"Apakah survey mencakup semua stakeholder: mahasiswa, dosen, tendik, mitra, lulusan, pengguna lulusan?","bobot":0}]');
INSERT INTO `Instrument` (`id`, `category`, `name`, `kriteria`, `indikator`, `jenjang_peruntukan`, `questions`) VALUES ('AK-35', 'Akuntabilitas', 'Zona Layanan Berintegritas (WBK/WBBM)', '-', '-', 'Semua', '[{"id":"q1","text":"Apakah terdapat dokumen peraturan layanan berintegritas di unit kerja?","bobot":0},{"id":"q2","text":"Apakah implementasi zona layanan berintegritas berjalan konsisten and terevaluasi?","bobot":0},{"id":"q3","text":"Apakah terdapat survey kepuasan stakeholder terkait layanan berintegritas?","bobot":0},{"id":"q4","text":"Apakah terdapat kick-off meeting komitmen WBK dan/atau WBBM?","bobot":0}]');
INSERT INTO `Instrument` (`id`, `category`, `name`, `kriteria`, `indikator`, `jenjang_peruntukan`, `questions`) VALUES ('DM-36', 'Diferensiasi Misi', 'Visi Keilmuan & Rencana Strategis Prodi', '-', '-', 'Semua', '[{"id":"q1","text":"Apakah UPPS memiliki visi keilmuan (keunggulan/penciri) prodi yang selaras dengan diferensiasi misi and visi PT?","bobot":0},{"id":"q2","text":"Apakah visi keilmuan didukung standar luaran, proses, and masukan tridharma yang relevan?","bobot":0},{"id":"q3","text":"Apakah pencapaian visi keilmuan dievaluasi untuk perbaikan berkelanjutan?","bobot":0},{"id":"q4","text":"Apakah rencana strategis pengembangan prodi mencakup peta pengembangan jangka panjang, menengah, and pendek dengan indikator terukur?","bobot":0},{"id":"q5","text":"Apakah rencana strategis mencakup pengembangan sarana, SDM, keuangan, tata kelola, kerjasama, and mahasiswa?","bobot":0},{"id":"q6","text":"Apakah renstra ditinjau secara berkala untuk mengakomodasi potensi risiko perubahan internal and eksternal?","bobot":0}]');
INSERT INTO `Instrument` (`id`, `category`, `name`, `kriteria`, `indikator`, `jenjang_peruntukan`, `questions`) VALUES ('DM-37', 'Diferensiasi Misi', 'Pelaksanaan Program Pendidikan & Pembelajaran', '-', '-', 'S1', '[{"id":"q1","text":"Apakah program pendidikan and pembelajaran sesuai dengan renstra/renop prodi?","bobot":0},{"id":"q2","text":"Apakah pendekatan project-based learning atau case method diterapkan untuk mengembangkan kompetensi mahasiswa? (fokus misi pendidikan)","bobot":0},{"id":"q3","text":"Apakah pendekatan research-based learning diterapkan untuk mengembangkan pengetahuan and mengasah mahasiswa menjadi seorang intelektual? (fokus misi penelitian)","bobot":0},{"id":"q4","text":"Apakah community service-based learning diterapkan melalui pemanfaatan pengetahuan and teknologi untuk menyelesaikan permasalahan masyarakat? (fokus misi PkM)","bobot":0},{"id":"q5","text":"Apakah program pendidikan and pembelajaran dievaluasi untuk perbaikan berkelanjutan?","bobot":0}]');
INSERT INTO `Instrument` (`id`, `category`, `name`, `kriteria`, `indikator`, `jenjang_peruntukan`, `questions`) VALUES ('DM-037', 'Diferensiasi Misi', 'Pelaksanaan Program Pendidikan & Pembelajaran', '-', '-', 'S2', '[{"id":"q1","text":"Apakah program pendidikan and pembelajaran sesuai dengan renstra/renop prodi?","bobot":0},{"id":"q2","text":"Apakah pendekatan research-based learning diterapkan untuk mengembangkan kompetensi mahasiswa sebagai peneliti? (fokus misi penelitian)","bobot":0},{"id":"q3","text":"Apakah pendekatan problem-based learning/case method diterapkan? (fokus misi pendidikan)","bobot":0},{"id":"q4","text":"Apakah community service-based learning diterapkan untuk menyelesaikan permasalahan masyarakat? (fokus misi PkM)","bobot":0},{"id":"q5","text":"Apakah program pendidikan and pembelajaran dievaluasi untuk perbaikan berkelanjutan?","bobot":0}]');
INSERT INTO `Instrument` (`id`, `category`, `name`, `kriteria`, `indikator`, `jenjang_peruntukan`, `questions`) VALUES ('DM-0037', 'Diferensiasi Misi', 'Pelaksanaan Program Pendidikan & Pembelajaran', '-', '-', 'S3', '[{"id":"q1","text":"Apakah program pendidikan and pembelajaran sesuai dengan renstra/renop prodi?","bobot":0},{"id":"q2","text":"Apakah pendekatan research-driven learning diterapkan untuk mengembangkan kompetensi mahasiswa sebagai peneliti? (fokus misi penelitian)","bobot":0},{"id":"q3","text":"Apakah pendekatan problem-based learning/case method diterapkan? (fokus misi pendidikan)","bobot":0},{"id":"q4","text":"Apakah community service-based learning diterapkan? (fokus misi PkM)","bobot":0},{"id":"q5","text":"Apakah program pendidikan and pembelajaran dievaluasi untuk perbaikan berkelanjutan?","bobot":0}]');
INSERT INTO `Instrument` (`id`, `category`, `name`, `kriteria`, `indikator`, `jenjang_peruntukan`, `questions`) VALUES ('DM-38', 'Diferensiasi Misi', 'Evaluasi Ketercapaian Tujuan Program Studi', '-', '-', 'Semua', '[{"id":"q1","text":"Apakah evaluasi keterlaksanaan and pencapaian program pendidikan sesuai diferensiasi misi dilakukan setiap tahun?","bobot":0},{"id":"q2","text":"Apakah terdapat kajian pembandingan capaian dengan institusi rujukan (benchmarking)?","bobot":0},{"id":"q3","text":"Apakah identifikasi perkembangan kebutuhan masyarakat/DUDIK untuk perbaikan prodi dilakukan?","bobot":0},{"id":"q4","text":"Apakah laporan ketercapaian tujuan program studi disampaikan kepada stakeholders?","bobot":0}]');
INSERT INTO `Instrument` (`id`, `category`, `name`, `kriteria`, `indikator`, `jenjang_peruntukan`, `questions`) VALUES ('DM-39', 'Diferensiasi Misi', 'Rekognisi & Apresiasi UPPS dari Masyarakat/DUDIK', '-', '-', 'S1', '[{"id":"q1","text":"Apakah terdapat permintaan kerjasama berkelanjutan terkait peningkatan kualitas pendidikan dari masyarakat/DUDIK? (fokus misi pendidikan)","bobot":0},{"id":"q2","text":"Apakah terdapat rekrutmen khusus lulusan dari DUDIK yang mengakui keunggulan prodi dalam literasi pedagogik and pemanfaatan TIK?","bobot":0},{"id":"q3","text":"Apakah lulusan memiliki sertifikasi profesional yang terbukti diakui industri?","bobot":0},{"id":"q4","text":"Apakah terdapat kolaborasi riset bersama DUDIK atau pemerintah? (fokus misi penelitian)","bobot":0},{"id":"q5","text":"Apakah produk riset prodi dimanfaatkan oleh industri/masyarakat?","bobot":0},{"id":"q6","text":"Apakah terdapat perubahan positif pada masyarakat/mitra PkM? (fokus misi PkM)","bobot":0},{"id":"q7","text":"Apakah terdapat kolaborasi PkM bersama masyarakat atau pemerintah yang berdampak?","bobot":0},{"id":"q8","text":"Apakah terdapat penghargaan dari pemerintah, industri, atau asosiasi profesi atas capaian prodi sesuai visi keilmuan?","bobot":0},{"id":"q9","text":"Apakah pengakuan and apresiasi terjadi pada level nasional and/atau internasional? (Syarat Perlu Terakreditasi Unggul)","bobot":0}]');
INSERT INTO `Instrument` (`id`, `category`, `name`, `kriteria`, `indikator`, `jenjang_peruntukan`, `questions`) VALUES ('DM-039', 'Diferensiasi Misi', 'Rekognisi & Apresiasi UPPS dari Masyarakat/DUDIK', '-', '-', 'S2', '[{"id":"q1","text":"Apakah terdapat permintaan kerjasama berkelanjutan terkait peningkatan kualitas pendidikan/penelitian/PkM dari masyarakat/DUDIK? (sesuai fokus misi)","bobot":0},{"id":"q2","text":"Apakah terdapat rekrutmen khusus lulusan dari DUDIK yang mengakui keunggulan prodi dalam pemanfaatan TIK and kompetensi lainnya?","bobot":0},{"id":"q3","text":"Apakah terdapat kolaborasi riset bersama DUDIK atau pemerintah? (fokus misi penelitian)","bobot":0},{"id":"q4","text":"Apakah produk riset prodi dimanfaatkan oleh industri/masyarakat?","bobot":0},{"id":"q5","text":"Apakah terdapat perubahan positif pada masyarakat/mitra PkM? (fokus misi PkM)","bobot":0},{"id":"q6","text":"Apakah terdapat kolaborasi PkM bersama masyarakat atau pemerintah yang berdampak?","bobot":0},{"id":"q7","text":"Apakah terdapat penghargaan dari pemerintah, industri, atau asosiasi profesi atas capaian prodi sesuai visi keilmuan?","bobot":0},{"id":"q8","text":"Apakah pengakuan and apresiasi terjadi pada level nasional and/atau internasional? (Syarat Perlu Terakreditasi Unggul)","bobot":0}]');
INSERT INTO `Instrument` (`id`, `category`, `name`, `kriteria`, `indikator`, `jenjang_peruntukan`, `questions`) VALUES ('DM-0039', 'Diferensiasi Misi', 'Rekognisi & Apresiasi UPPS dari Masyarakat/DUDIK', '-', '-', 'S3', '[{"id":"q1","text":"Apakah terdapat permintaan kerjasama berkelanjutan terkait peningkatan kualitas pendidikan/penelitian/PkM dari masyarakat/DUDIK? (sesuai fokus misi)","bobot":0},{"id":"q2","text":"Apakah terdapat rekrutmen khusus lulusan dari DUDIK yang mengakui keunggulan prodi?","bobot":0},{"id":"q3","text":"Apakah terdapat kolaborasi riset bersama DUDIK atau pemerintah? (fokus misi penelitian)","bobot":0},{"id":"q4","text":"Apakah produk riset prodi dimanfaatkan oleh industri/masyarakat?","bobot":0},{"id":"q5","text":"Apakah terdapat perubahan positif pada masyarakat/mitra PkM? (fokus misi PkM)","bobot":0},{"id":"q6","text":"Apakah terdapat kolaborasi PkM bersama masyarakat atau pemerintah yang berdampak?","bobot":0},{"id":"q7","text":"Apakah terdapat penghargaan dari pemerintah, industri, atau asosiasi profesi atas capaian prodi sesuai visi keilmuan?","bobot":0},{"id":"q8","text":"Apakah pengakuan and apresiasi terjadi pada level nasional and/atau internasional? (Syarat Perlu Terakreditasi Unggul)","bobot":0}]');
INSERT INTO `Instrument` (`id`, `category`, `name`, `kriteria`, `indikator`, `jenjang_peruntukan`, `questions`) VALUES ('TL-1', 'Tindak Lanjut', 'Tindak Lanjut Hasil MONEV', '-', '-', 'Semua', '[{"id":"q1","text":"Apakah seluruh temuan hasil MONEV semester berjalan telah direkap and diklasifikasikan?","bobot":0},{"id":"q2","text":"Apakah tindak lanjut telah ditetapkan untuk setiap temuan MONEV?","bobot":0},{"id":"q3","text":"Apakah penanggung jawab and tenggat waktu tindak lanjut ditetapkan?","bobot":0},{"id":"q4","text":"Apakah tindak lanjut hasil MONEV dikomunikasikan kepada pihak terkait?","bobot":0}]');
INSERT INTO `Instrument` (`id`, `category`, `name`, `kriteria`, `indikator`, `jenjang_peruntukan`, `questions`) VALUES ('TL-2', 'Tindak Lanjut', 'Pemantauan Tindak Lanjut Hasil MONEV', '-', '-', 'Semua', '[{"id":"q1","text":"Apakah pemantauan pelaksanaan tindak lanjut MONEV dilakukan secara terjadwal?","bobot":0},{"id":"q2","text":"Apakah status tindak lanjut (selesai/dalam proses/belum) terdokumentasi?","bobot":0},{"id":"q3","text":"Apakah efektivitas tindak lanjut dievaluasi untuk MONEV periode berikutnya?","bobot":0},{"id":"q4","text":"Apakah laporan pemantauan tindak lanjut disampaikan ke pimpinan UPPS/PT?","bobot":0}]');

-- Data for table `MonevRecord`
INSERT INTO `MonevRecord` (`id`, `prodiId`, `instrumentId`, `tahun_akademik`, `semester`, `analisa_kpma`, `tindak_lanjut_kpma`, `answers`, `updatedAt`) VALUES ('cmok5ytxg0001ot9gt7qst7ah', 'cmoj7qv6j000eot5o8oiezdnp', 'BM-1', '2025/2026', 'Ganjil', '', '', '{"q1":{"pilihan":"Ya","buktiLinks":[]},"q2":{"pilihan":"Ya","buktiLinks":[]}}', '2026-04-29 23:24:17');
INSERT INTO `MonevRecord` (`id`, `prodiId`, `instrumentId`, `tahun_akademik`, `semester`, `analisa_kpma`, `tindak_lanjut_kpma`, `answers`, `updatedAt`) VALUES ('cmok6t7v00001ote4grk86egl', 'cmoj7qv6j000eot5o8oiezdnp', 'BM-2', '2025/2026', 'Ganjil', '', '', '{"q1":{"pilihan":"Ya","buktiLinks":["https://drive.google.com/file/d/1UACcrN0vSufGJXBtFxlSbq5pKT01R0fB/view?usp=drivesdk"]}}', '2026-04-29 15:05:50');
INSERT INTO `MonevRecord` (`id`, `prodiId`, `instrumentId`, `tahun_akademik`, `semester`, `analisa_kpma`, `tindak_lanjut_kpma`, `answers`, `updatedAt`) VALUES ('cmokruuqi0001otnosekhmmst', 'cmoj7qv6j000eot5o8oiezdnp', 'BM-3', '2025/2026', 'Ganjil', '', '', '{"q1":{"pilihan":"Ya","buktiLinks":[]}}', '2026-04-30 04:46:08');

SET FOREIGN_KEY_CHECKS = 1;
